# 9 WorkFlow Analista Senior

### 9.5 Objetivo

Presentar un workflow/pipeline completo al que los estudiantes deberán
enriquecer
<br>El Analista Sr corre sus scripts en máquinas virtuales de al menos 128 GB de RAM en Toronto, creando una virtual machine para cada corrida.
<br>Estas virtual machines se auto-suicidarán a los 30 minutos de haber terminado de procesar.

## 9.7  Workflow

## Inicializacion

Esta parte se debe correr con el runtime en lenguaje **R** Ir al menu, Runtime -> Change Runtime Type -> Runtime type -> R

limpio el ambiente de R

In [1]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Thu Sep 03 21:02:26 2026"

In [2]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  671179 35.9 1479894    79.1 1354606  72.4
Vcells 1242556  9.5 8388608    64.0 1978703  15.1

In [3]:
require("data.table")

if( !require("R.utils")) install.packages("R.utils")
require("R.utils")

Loading required package: data.table

Attaching package: ‘data.table’

The following object is masked from ‘package:base’:

    %notin%

Loading required package: R.utils

Loading required package: R.oo

Loading required package: R.methodsS3

R.methodsS3 v1.8.2 (2022-06-13 22:00:14 UTC) successfully loaded. See ?R.methodsS3 for help.

R.oo v1.27.1 (2025-05-02 21:00:05 UTC) successfully loaded. See ?R.oo for help.

Attaching package: ‘R.oo’

The following object is masked from ‘package:R.methodsS3’:

    throw

The following objects are masked from ‘package:methods’:

    getClasses, getMethods

The following objects are masked from ‘package:base’:

    attach, detach, load, save

R.utils v2.13.0 (2025-02-24 21:20:02 UTC) successfully loaded. See ?R.utils for help.

Attaching package: ‘R.utils’

The following object is masked from ‘package:utils’:

    timestamp

The following objects are masked from ‘package:base’:

    cat, commandArgs, getOption, isOpen, nullfile, parse, use, warnings

#### Parametros

In [4]:
PARAM <- list()
# semilla tomada de la variable de ambiente SEMILLA
#  si no existe, se usa la semilla del baseline  300089
PARAM$semilla_primigenia <- as.integer(Sys.getenv("SEMILLA", "300089"))

# numero de experimento tomado de la variable de ambiente EXP_NUM
#  es obligatorio: si no existe, se corta la ejecucion
#  (evita pisar por accidente corridas previas con el 9500 base)
if (Sys.getenv("EXP_NUM") == "") {
  stop("Variable de ambiente EXP_NUM no definida (numero de experimento)")
}
PARAM$experimento <- as.integer(Sys.getenv("EXP_NUM"))
PARAM$dataset <- "analistasr_competencia_2026.csv.gz"

# selector de variables FORZADO a canarito (no Boruta, warm-start canarito only)
PARAM$FS$selector <- "canarito"

# parametros de Boruta, tomados de variables de ambiente con defaults
PARAM$BR$ntree         <- as.integer(Sys.getenv("BR_NTREE", "50"))
PARAM$BR$maxRuns       <- as.integer(Sys.getenv("BR_MAXRUNS", "12"))
PARAM$BR$pValue        <- as.numeric(Sys.getenv("BR_PVALUE", "0.05"))
PARAM$BR$mcAdj         <- Sys.getenv("BR_MCADJ", "TRUE") == "TRUE"
PARAM$BR$undersampling <- as.numeric(Sys.getenv("BR_UNDERSAMPLING", "0.10"))
PARAM$BR$holdHistory   <- Sys.getenv("BR_HOLDHISTORY", "TRUE") == "TRUE"
# hilos para ranger; 12 = default para VM de 12 vCPUs (0 = auto/no set)
PARAM$BR$threads       <- as.integer(Sys.getenv("BR_THREADS", "12"))
# pesos de clase para el RF de Boruta; FALSE = version vanilla
#  (Canaritos tampoco usa pesos, solo undersampling)
PARAM$BR$classweights  <- Sys.getenv("BR_CLASSWEIGHTS", "FALSE") == "TRUE"
# Boruta exige maxRuns > 10
if( PARAM$BR$maxRuns <= 10 ) {
  stop("BR_MAXRUNS debe ser mayor a 10 (requisito de Boruta)")
}

#### Carpeta del Experimento

In [5]:
# carpeta de trabajo
#  se agrega la semilla al nombre para que cada corrida independiente
#  tenga su propia carpeta y no se pisen los archivos

setwd("/content/buckets/b1/exp")
experimento_folder <- paste0("WF", PARAM$experimento, "_s", PARAM$semilla_primigenia)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento_folder ))

### 9.7.1   Preprocesamiento del dataset

#### 9.7.1.1  DT incorporar dataset

In [6]:
# lectura del dataset
dataset <- fread(paste0("/content/datasets/", PARAM$dataset))

#### 9.7.1.2  CA  Catastrophe Analysis
Se intentan reparar las variables que para un mes están con todos los valores en cero.

El método que se utiliza es **Machine Learning** se asigna NA also valores, si ha leido bien, es la "anti imputación de valores faltantes"
<br> Usted podrá aplicar aquí otros métodos

In [7]:
if( !require("mice")) install.packages("mice", repos = "http://cran.us.r-project.org")
require("mice")

Loading required package: mice

Attaching package: ‘mice’

The following object is masked from ‘package:stats’:

    filter

The following objects are masked from ‘package:base’:

    cbind, rbind

In [8]:
# Escrito por alumnos de  Universidad Austral  Rosario

Corregir_MICE <- function(pcampo, pmeses) {

  meth <- rep("", ncol(dataset))
  names(meth) <- colnames(dataset)
  meth[names(meth) == pcampo] <- "sample"

  # llamada a mice  !
  imputacion <- mice(dataset,
    method = meth,
    maxit = 5,
    m = 1,
    seed = 7)

  tbl <- mice::complete(dataset)

  dataset[, paste0(pcampo) := ifelse(foto_mes %in% pmeses, tbl[, get(pcampo)], get(pcampo))]

}

In [9]:
Corregir_interpolar <- function(pcampo, pmeses) {

  tbl <- dataset[, list(
    "v1" = shift(get(pcampo), 1, type = "lag"),
    "v2" = shift(get(pcampo), 1, type = "lead")
  ),
  by = eval(PARAM$dataset_metadata$entity_id)
  ]

  tbl[, paste0(PARAM$dataset_metadata$entity_id) := NULL]
  tbl[, promedio := rowMeans(tbl, na.rm = TRUE)]

  dataset[
    ,
    paste0(pcampo) := ifelse(!(foto_mes %in% pmeses),
      get(pcampo),
      tbl$promedio
    )
  ]
}

In [10]:
AsignarNA_campomeses <- function(pcampo, pmeses) {

  if( pcampo %in% colnames( dataset ) ) {

    dataset[ foto_mes %in% pmeses, paste0(pcampo) := NA ]
  }
}

In [11]:

Corregir_atributo <- function(pcampo, pmeses, pmetodo)
{
  # si el campo no existe en el dataset, Afuera !
  if( !(pcampo %in% colnames( dataset )) )
    return( 1 )

  # llamo a la funcion especializada que corresponde
  switch( pmetodo,
    "MachineLearning"     = AsignarNA_campomeses(pcampo, pmeses),
    "EstadisticaClasica"  = Corregir_interpolar(pcampo, pmeses),
    "MICE"                = Corregir_MICE(pcampo, pmeses),
  )

  return( 0 )
}

In [12]:

Corregir_Rotas <- function(dataset, pmetodo) {
  gc(verbose= FALSE)
  cat( "inicio Corregir_Rotas()\n")
  # acomodo los errores del dataset

  Corregir_atributo("active_quarter", c(202006), pmetodo) # 1
  Corregir_atributo("internet", c(202006), pmetodo) # 2

  Corregir_atributo("mrentabilidad", c(201905, 201910, 202006), pmetodo) # 3
  Corregir_atributo("mrentabilidad_annual", c(201905, 201910, 202006), pmetodo) # 4

  Corregir_atributo("mcomisiones", c(201905, 201910, 202006), pmetodo) # 5

  Corregir_atributo("mactivos_margen", c(201905, 201910, 202006), pmetodo) # 6
  Corregir_atributo("mpasivos_margen", c(201905, 201910, 202006), pmetodo) # 7

  Corregir_atributo("mcuentas_saldo", c(202006), pmetodo) # 8

  Corregir_atributo("ctarjeta_debito_transacciones", c(202006), pmetodo) # 9

  Corregir_atributo("mautoservicio", c(202006), pmetodo) # 10

  Corregir_atributo("ctarjeta_visa_transacciones", c(202006), pmetodo) # 11
  Corregir_atributo("mtarjeta_visa_consumo", c(202006), pmetodo) # 12

  Corregir_atributo("ctarjeta_master_transacciones", c(202006), pmetodo) # 13
  Corregir_atributo("mtarjeta_master_consumo", c(202006), pmetodo) # 14

  Corregir_atributo("ctarjeta_visa_debitos_automaticos", c(201904), pmetodo) # 15
  Corregir_atributo("mttarjeta_visa_debitos_automaticos", c(201904), pmetodo) # 16

  Corregir_atributo("ccajeros_propios_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 17

  Corregir_atributo("mcajeros_propios_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 18

  Corregir_atributo("ctarjeta_visa_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 19

  Corregir_atributo("mtarjeta_visa_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 20

  Corregir_atributo("ctarjeta_master_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 21

  Corregir_atributo("mtarjeta_master_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 22

  Corregir_atributo("ccomisiones_otras", c(201905, 201910, 202006), pmetodo) # 23
  Corregir_atributo("mcomisiones_otras", c(201905, 201910, 202006), pmetodo) # 24

  Corregir_atributo("cextraccion_autoservicio", c(202006), pmetodo) # 25
  Corregir_atributo("mextraccion_autoservicio", c(202006), pmetodo) # 26

  Corregir_atributo("ccheques_depositados", c(202006), pmetodo) # 27
  Corregir_atributo("mcheques_depositados", c(202006), pmetodo) # 28
  Corregir_atributo("ccheques_emitidos", c(202006), pmetodo) # 29
  Corregir_atributo("mcheques_emitidos", c(202006), pmetodo) # 30
  Corregir_atributo("ccheques_depositados_rechazados", c(202006), pmetodo) # 31
  Corregir_atributo("mcheques_depositados_rechazados", c(202006), pmetodo) # 32
  Corregir_atributo("ccheques_emitidos_rechazados", c(202006), pmetodo) # 33
  Corregir_atributo("mcheques_emitidos_rechazados", c(202006), pmetodo) # 34

  Corregir_atributo("tcallcenter", c(202006), pmetodo) # 35
  Corregir_atributo("ccallcenter_transacciones", c(202006), pmetodo) # 36

  Corregir_atributo("thomebanking", c(202006), pmetodo) # 37
  Corregir_atributo("chomebanking_transacciones", c(201910, 202006), pmetodo) # 38

  Corregir_atributo("ccajas_transacciones", c(202006), pmetodo) # 39
  Corregir_atributo("ccajas_consultas", c(202006), pmetodo) # 40

  Corregir_atributo("ccajas_depositos", c(202006, 202105), pmetodo) # 41

  Corregir_atributo("ccajas_extracciones", c(202006), pmetodo) # 41
  Corregir_atributo("ccajas_otras", c(202006), pmetodo) # 43

  Corregir_atributo("catm_trx", c(202006), pmetodo) # 44
  Corregir_atributo("matm", c(202006), pmetodo) # 45
  Corregir_atributo("catm_trx_other", c(202006), pmetodo) # 46
  Corregir_atributo("matm_other", c(202006), pmetodo) # 47

  cat( "fin Corregir_rotas()\n")
}

In [13]:
# resuelvo el Catastrophe Analysis

setorder( dataset, numero_de_cliente, foto_mes )

PARAM$CA$metodo= "MachineLearning"

if( PARAM$CA$metodo %in% c("MachineLearning", "EstadisticaClasica", "MICE") )
  Corregir_Rotas(dataset, PARAM$CA$metodo)

inicio Corregir_Rotas()
fin Corregir_rotas()

#### 9.7.1.3  DR  Data Drifting
Se intenta corregir el data drifting, ajustando por algunos indices financieros

In [14]:
# meses que me interesan para el ajuste de variables monetarias
vfoto_mes <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105, 202106,
  202107, 202108, 202109
)

In [15]:
# los valores que siguen fueron calculados por alumnos

# momento 1.0  31-dic-2020 a las 23:59
vIPC <- c(
  1.9903030878, 1.9174403544, 1.8296186587,
  1.7728862972, 1.7212488323, 1.6776304408,
  1.6431248196, 1.5814483345, 1.4947526791,
  1.4484037589, 1.3913580777, 1.3404220402,
  1.3154288912, 1.2921698342, 1.2472681797,
  1.2300475145, 1.2118694724, 1.1881073259,
  1.1693969743, 1.1375456949, 1.1065619600,
  1.0681100000, 1.0370000000, 1.0000000000,
  0.9680542110, 0.9344152616, 0.8882274350,
  0.8532444140, 0.8251880213, 0.8003763543,
  0.7763107219, 0.7566381305, 0.7289384687
)

vdolar_blue <- c(
   39.045455,  38.402500,  41.639474,
   44.274737,  46.095455,  45.063333,
   43.983333,  54.842857,  61.059524,
   65.545455,  66.750000,  72.368421,
   77.477273,  78.191667,  82.434211,
  101.087500, 126.236842, 125.857143,
  130.782609, 133.400000, 137.954545,
  170.619048, 160.400000, 153.052632,
  157.900000, 149.780952, 143.615385,
  146.250000, 153.550000, 162.000000,
  178.478261, 180.878788, 184.357143
)

vdolar_oficial <- c(
   38.430000,  39.428000,  42.542105,
   44.354211,  46.088636,  44.955000,
   43.751429,  54.650476,  58.790000,
   61.403182,  63.012632,  63.011579,
   62.983636,  63.580556,  65.200000,
   67.872000,  70.047895,  72.520952,
   75.324286,  77.488500,  79.430909,
   83.134762,  85.484737,  88.181667,
   91.474000,  93.997778,  96.635909,
   98.526000,  99.613158, 100.619048,
  101.619048, 102.569048, 103.781818
)

vUVA <- c(
  2.001408838932958,  1.950325472789153,  1.89323032351521,
  1.8247220405493787, 1.746027787673673,  1.6871348409529485,
  1.6361678865622313, 1.5927529755859773, 1.5549162794128493,
  1.4949100586391746, 1.4197729500774545, 1.3678188186372326,
  1.3136508617223726, 1.2690535173062818, 1.2381595983200178,
  1.211656735577568,  1.1770808941405335, 1.1570338657445522,
  1.1388769475653255, 1.1156993751209352, 1.093638313080772,
  1.0657171590878205, 1.0362173587708712, 1.0,
  0.9669867858358365, 0.9323750098728378, 0.8958202912590305,
  0.8631993702994263, 0.8253893405524657, 0.7928918905364516,
  0.7666323845128089, 0.7428976357662823, 0.721615762047849
)

In [16]:
tb_indices <- as.data.table( list(
  "IPC" = vIPC,
  "dolar_blue" = vdolar_blue,
  "dolar_oficial" = vdolar_oficial,
  "UVA" = vUVA
  )
)

tb_indices[[ 'foto_mes' ]] <- vfoto_mes

tb_indices

   IPC       dolar_blue dolar_oficial UVA       foto_mes
1  1.9903031  39.04545   38.43000     2.0014088 201901
2  1.9174404  38.40250   39.42800     1.9503255 201902
3  1.8296187  41.63947   42.54210     1.8932303 201903
4  1.7728863  44.27474   44.35421     1.8247220 201904
5  1.7212488  46.09546   46.08864     1.7460278 201905
6  1.6776304  45.06333   44.95500     1.6871348 201906
7  1.6431248  43.98333   43.75143     1.6361679 201907
8  1.5814483  54.84286   54.65048     1.5927530 201908
9  1.4947527  61.05952   58.79000     1.5549163 201909
10 1.4484038  65.54546   61.40318     1.4949101 201910
11 1.3913581  66.75000   63.01263     1.4197730 201911
12 1.3404220  72.36842   63.01158     1.3678188 201912
13 1.3154289  77.47727   62.98364     1.3136509 202001
14 1.2921698  78.19167   63.58056     1.2690535 202002
15 1.2472682  82.43421   65.20000     1.2381596 202003
16 1.2300475 101.08750   67.87200     1.2116567 202004
17 1.2118695 126.23684   70.04789     1.1770809 202005
18 1.1881073 125.85714   72.52095     1.1570339 202006
19 1.1693970 130.78261   75.32429     1.1388769 202007
20 1.1375457 133.40000   77.48850     1.1156994 202008
21 1.1065620 137.95454   79.43091     1.0936383 202009
22 1.0681100 170.61905   83.13476     1.0657172 202010
23 1.0370000 160.40000   85.48474     1.0362174 202011
24 1.0000000 153.05263   88.18167     1.0000000 202012
25 0.9680542 157.90000   91.47400     0.9669868 202101
26 0.9344153 149.78095   93.99778     0.9323750 202102
27 0.8882274 143.61539   96.63591     0.8958203 202103
28 0.8532444 146.25000   98.52600     0.8631994 202104
29 0.8251880 153.55000   99.61316     0.8253893 202105
30 0.8003764 162.00000  100.61905     0.7928919 202106
31 0.7763107 178.47826  101.61905     0.7666324 202107
32 0.7566381 180.87879  102.56905     0.7428976 202108
33 0.7289385 184.35714  103.78182     0.7216158 202109

In [17]:
drift_UVA <- function(campos_monetarios) {
  cat( "inicio drift_UVA()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD * i.UVA,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_UVA()\n")
}

In [18]:
drift_dolar_oficial <- function(campos_monetarios) {
  cat( "inicio drift_dolar_oficial()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD / i.dolar_oficial,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_dolar_oficial()\n")
}

In [19]:
drift_dolar_blue <- function(campos_monetarios) {
  cat( "inicio drift_dolar_blue()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD / i.dolar_blue,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_dolar_blue()\n")
}

In [20]:
drift_deflacion <- function(campos_monetarios) {
  cat( "inicio drift_deflacion()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD * i.IPC,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_deflacion()\n")
}

In [21]:
drift_rank_simple <- function(campos_drift) {

  cat( "inicio drift_rank_simple()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[, paste0(campo, "_rank") :=
      (frank(get(campo), ties.method = "random") - 1) / (.N - 1), by = list(foto_mes)]
    dataset[, (campo) := NULL]
  }
  cat( "fin drift_rank_simple()\n")
}

In [22]:
# El cero se transforma en cero
# los positivos se rankean por su lado
# los negativos se rankean por su lado

drift_rank_cero_fijo <- function(campos_drift) {

  cat( "inicio drift_rank_cero_fijo()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[get(campo) == 0, paste0(campo, "_rank") := 0]
    dataset[get(campo) > 0, paste0(campo, "_rank") :=
      frank(get(campo), ties.method = "random") / .N, by = list(foto_mes)]

    dataset[get(campo) < 0, paste0(campo, "_rank") :=
      -frank(-get(campo), ties.method = "random") / .N, by = list(foto_mes)]
    dataset[, (campo) := NULL]
  }
  cat("\n")
  cat( "fin drift_rank_cero_fijo()\n")
}

In [23]:
drift_estandarizar <- function(campos_drift) {

  cat( "inicio drift_estandarizar()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[, paste0(campo, "_normal") :=
      (get(campo) -mean(campo, na.rm=TRUE)) / sd(get(campo), na.rm=TRUE),
      by = list(foto_mes)]

    dataset[, (campo) := NULL]
  }
  cat( "fin drift_estandarizar()\n")
}

In [24]:
# por como armé los nombres de campos,
#  estos son los campos que expresan variables monetarias
campos_monetarios <- colnames(dataset)
campos_monetarios <- campos_monetarios[campos_monetarios %like%
  "^(m|Visa_m|Master_m|vm_m)"]

campos_monetarios

 [1] "mrentabilidad"
 [2] "mrentabilidad_annual"
 [3] "mcomisiones"
 [4] "mactivos_margen"
 [5] "mpasivos_margen"
 [6] "mcuenta_corriente_adicional"
 [7] "mcuenta_corriente"
 [8] "mcaja_ahorro"
 [9] "mcaja_ahorro_adicional"
[10] "mcaja_ahorro_dolares"
[11] "mcuentas_saldo"
[12] "mautoservicio"
[13] "mtarjeta_visa_consumo"
[14] "mtarjeta_master_consumo"
[15] "mprestamos_personales"
[16] "mprestamos_prendarios"
[17] "mprestamos_hipotecarios"
[18] "mplazo_fijo_dolares"
[19] "mplazo_fijo_pesos"
[20] "minversion1_pesos"
[21] "minversion1_dolares"
[22] "minversion2"
[23] "mpayroll"
[24] "mpayroll2"
[25] "mcuenta_debitos_automaticos"
[26] "mttarjeta_visa_debitos_automaticos"
[27] "mttarjeta_master_debitos_automaticos"
[28] "mpagodeservicios"
[29] "mpagomiscuentas"
[30] "mcajeros_propios_descuentos"
[31] "mtarjeta_visa_descuentos"
[32] "mtarjeta_master_descuentos"
[33] "mcomisiones_mantenimiento"
[34] "mcomisiones_otras"
[35] "mforex_buy"
[36] "mforex_sell"
[37] "mtransferencias_recibidas"
[38] "mtransferencias_emitidas"
[39] "mextraccion_autoservicio"
[40] "mcheques_depositados"
[41] "mcheques_emitidos"
[42] "mcheques_depositados_rechazados"
[43] "mcheques_emitidos_rechazados"
[44] "matm"
[45] "matm_other"
[46] "Master_mfinanciacion_limite"
[47] "Master_msaldototal"
[48] "Master_msaldopesos"
[49] "Master_msaldodolares"
[50] "Master_mconsumospesos"
[51] "Master_mconsumosdolares"
[52] "Master_mlimitecompra"
[53] "Master_madelantopesos"
[54] "Master_madelantodolares"
[55] "Master_mpagado"
[56] "Master_mpagospesos"
[57] "Master_mpagosdolares"
[58] "Master_mconsumototal"
[59] "Master_mpagominimo"
[60] "Visa_mfinanciacion_limite"
[61] "Visa_msaldototal"
[62] "Visa_msaldopesos"
[63] "Visa_msaldodolares"
[64] "Visa_mconsumospesos"
[65] "Visa_mconsumosdolares"
[66] "Visa_mlimitecompra"
[67] "Visa_madelantopesos"
[68] "Visa_madelantodolares"
[69] "Visa_mpagado"
[70] "Visa_mpagospesos"
[71] "Visa_mpagosdolares"
[72] "Visa_mconsumototal"
[73] "Visa_mpagominimo"

In [25]:
# ejecuto el Data Drifting
setorder( dataset, numero_de_cliente, foto_mes )


PARAM$DR$metodo <- "rank_cero_fijo"

switch(PARAM$DR$metodo,
  "ninguno"        = cat("No hay correccion del data drifting"),
  "rank_simple"    = drift_rank_simple(campos_monetarios),
  "rank_cero_fijo" = drift_rank_cero_fijo(campos_monetarios),
  "deflacion"      = drift_deflacion(campos_monetarios),
  "dolar_blue"     = drift_dolarblue(campos_monetarios),
  "dolar_oficial"  = drift_dolaroficial(campos_monetarios),
  "UVA"            = drift_UVA(campos_monetarios),
  "estandarizar"   = drift_estandarizar(campos_monetarios)
)

inicio drift_rank_cero_fijo()
mrentabilidad  mrentabilidad_annual  mcomisiones  mactivos_margen  mpasivos_margen  mcuenta_corriente_adicional  mcuenta_corriente  mcaja_ahorro  mcaja_ahorro_adicional  mcaja_ahorro_dolares  mcuentas_saldo  mautoservicio  mtarjeta_visa_consumo  mtarjeta_master_consumo  mprestamos_personales  mprestamos_prendarios  mprestamos_hipotecarios  mplazo_fijo_dolares  mplazo_fijo_pesos  minversion1_pesos  minversion1_dolares  minversion2  mpayroll  mpayroll2  mcuenta_debitos_automaticos  mttarjeta_visa_debitos_automaticos  mttarjeta_master_debitos_automaticos  mpagodeservicios  mpagomiscuentas  mcajeros_propios_descuentos  mtarjeta_visa_descuentos  mtarjeta_master_descuentos  mcomisiones_mantenimiento  mcomisiones_otras  mforex_buy  mforex_sell  mtransferencias_recibidas  mtransferencias_emitidas  mextraccion_autoservicio  mcheques_depositados  mcheques_emitidos  mcheques_depositados_rechazados  mcheques_emitidos_rechazados  matm  matm_other  Master_mfinanciacion_limite  Master_msaldototal  Master_msaldopesos  Master_msaldodolares  Master_mconsumospesos  Master_mconsumosdolares  Master_mlimitecompra  Master_madelantopesos  Master_madelantodolares  Master_mpagado  Master_mpagospesos  Master_mpagosdolares  Master_mconsumototal  Master_mpagominimo  Visa_mfinanciacion_limite  Visa_msaldototal  Visa_msaldopesos  Visa_msaldodolares  Visa_mconsumospesos  Visa_mconsumosdolares  Visa_mlimitecompra  Visa_madelantopesos  Visa_madelantodolares  Visa_mpagado  Visa_mpagospesos  Visa_mpagosdolares  Visa_mconsumototal  Visa_mpagominimo
fin drift_rank_cero_fijo()

In [26]:
colnames(dataset)

  [1] "numero_de_cliente"
  [2] "foto_mes"
  [3] "active_quarter"
  [4] "cliente_vip"
  [5] "internet"
  [6] "cliente_edad"
  [7] "cliente_antiguedad"
  [8] "cproductos"
  [9] "tcuentas"
 [10] "ccuenta_corriente"
 [11] "ccaja_ahorro"
 [12] "cdescubierto_preacordado"
 [13] "ctarjeta_debito"
 [14] "ctarjeta_debito_transacciones"
 [15] "ctarjeta_visa"
 [16] "ctarjeta_visa_transacciones"
 [17] "ctarjeta_master"
 [18] "ctarjeta_master_transacciones"
 [19] "cprestamos_personales"
 [20] "cprestamos_prendarios"
 [21] "cprestamos_hipotecarios"
 [22] "cplazo_fijo"
 [23] "cinversion1"
 [24] "cinversion2"
 [25] "cseguro_vida"
 [26] "cseguro_auto"
 [27] "cseguro_vivienda"
 [28] "cseguro_accidentes_personales"
 [29] "ccaja_seguridad"
 [30] "cpayroll_trx"
 [31] "cpayroll2_trx"
 [32] "ccuenta_debitos_automaticos"
 [33] "ctarjeta_visa_debitos_automaticos"
 [34] "ctarjeta_master_debitos_automaticos"
 [35] "cpagodeservicios"
 [36] "cpagomiscuentas"
 [37] "ccajeros_propios_descuentos"
 [38] "ctarjeta_visa_descuentos"
 [39] "ctarjeta_master_descuentos"
 [40] "ccomisiones_mantenimiento"
 [41] "ccomisiones_otras"
 [42] "cforex"
 [43] "cforex_buy"
 [44] "cforex_sell"
 [45] "ctransferencias_recibidas"
 [46] "ctransferencias_emitidas"
 [47] "cextraccion_autoservicio"
 [48] "ccheques_depositados"
 [49] "ccheques_emitidos"
 [50] "ccheques_depositados_rechazados"
 [51] "ccheques_emitidos_rechazados"
 [52] "tcallcenter"
 [53] "ccallcenter_transacciones"
 [54] "thomebanking"
 [55] "chomebanking_transacciones"
 [56] "ccajas_transacciones"
 [57] "ccajas_consultas"
 [58] "ccajas_depositos"
 [59] "ccajas_extracciones"
 [60] "ccajas_otras"
 [61] "catm_trx"
 [62] "catm_trx_other"
 [63] "ctrx_quarter"
 [64] "tmobile_app"
 [65] "cmobile_app_trx"
 [66] "Master_delinquency"
 [67] "Master_status"
 [68] "Master_Fvencimiento"
 [69] "Master_Finiciomora"
 [70] "Master_fultimo_cierre"
 [71] "Master_fechaalta"
 [72] "Master_cconsumos"
 [73] "Master_cadelantosefectivo"
 [74] "Visa_delinquency"
 [75] "Visa_status"
 [76] "Visa_Fvencimiento"
 [77] "Visa_Finiciomora"
 [78] "Visa_fultimo_cierre"
 [79] "Visa_fechaalta"
 [80] "Visa_cconsumos"
 [81] "Visa_cadelantosefectivo"
 [82] "clase_ternaria"
 [83] "mrentabilidad_rank"
 [84] "mrentabilidad_annual_rank"
 [85] "mcomisiones_rank"
 [86] "mactivos_margen_rank"
 [87] "mpasivos_margen_rank"
 [88] "mcuenta_corriente_adicional_rank"
 [89] "mcuenta_corriente_rank"
 [90] "mcaja_ahorro_rank"
 [91] "mcaja_ahorro_adicional_rank"
 [92] "mcaja_ahorro_dolares_rank"
 [93] "mcuentas_saldo_rank"
 [94] "mautoservicio_rank"
 [95] "mtarjeta_visa_consumo_rank"
 [96] "mtarjeta_master_consumo_rank"
 [97] "mprestamos_personales_rank"
 [98] "mprestamos_prendarios_rank"
 [99] "mprestamos_hipotecarios_rank"
[100] "mplazo_fijo_dolares_rank"
[101] "mplazo_fijo_pesos_rank"
[102] "minversion1_pesos_rank"
[103] "minversion1_dolares_rank"
[104] "minversion2_rank"
[105] "mpayroll_rank"
[106] "mpayroll2_rank"
[107] "mcuenta_debitos_automaticos_rank"
[108] "mttarjeta_visa_debitos_automaticos_rank"
[109] "mttarjeta_master_debitos_automaticos_rank"
[110] "mpagodeservicios_rank"
[111] "mpagomiscuentas_rank"
[112] "mcajeros_propios_descuentos_rank"
[113] "mtarjeta_visa_descuentos_rank"
[114] "mtarjeta_master_descuentos_rank"
[115] "mcomisiones_mantenimiento_rank"
[116] "mcomisiones_otras_rank"
[117] "mforex_buy_rank"
[118] "mforex_sell_rank"
[119] "mtransferencias_recibidas_rank"
[120] "mtransferencias_emitidas_rank"
[121] "mextraccion_autoservicio_rank"
[122] "mcheques_depositados_rank"
[123] "mcheques_emitidos_rank"
[124] "mcheques_depositados_rechazados_rank"
[125] "mcheques_emitidos_rechazados_rank"
[126] "matm_rank"
[127] "matm_other_rank"
[128] "Master_mfinanciacion_limite_rank"
[129] "Master_msaldototal_rank"
[130] "Master_msaldopesos_rank"
[131] "Master_msaldodolares_rank"
[132] "Master_mconsumospesos_rank"
[133] "Master_mconsumosdolares_rank"
[134] "Master_mlimitecompra_rank"
[135] "Master_madelantopesos_rank"
[136] "Master_madelantodolares_rank"
[137] "Master_mpagado_rank"
[138] "Master_mpagospesos_rank"
[139] "Master_mpagosdolares_rank"
[140] "Master_mconsumototal_rank"
[141] "Master_mpagominimo_rank"
[142] "Visa_mfinanciacion_limite_rank"
[143] "Visa_msaldototal_rank"
[144] "Visa_msaldopesos_rank"
[145] "Visa_msaldodolares_rank"
[146] "Visa_mconsumospesos_rank"
[147] "Visa_mconsumosdolares_rank"
[148] "Visa_mlimitecompra_rank"
[149] "Visa_madelantopesos_rank"
[150] "Visa_madelantodolares_rank"
[151] "Visa_mpagado_rank"
[152] "Visa_mpagospesos_rank"
[153] "Visa_mpagosdolares_rank"
[154] "Visa_mconsumototal_rank"
[155] "Visa_mpagominimo_rank"

#### 9.7.1.3  FE_intra_manual Feature Engineering intra-mes

Agrego campos nuevos dentro del mismo mes, SIN considerar la historia.

In [27]:
if( !require("lubridate")) install.packages("lubridate", repos = "http://cran.us.r-project.org")
require("lubridate")

Loading required package: lubridate

Attaching package: ‘lubridate’

The following objects are masked from ‘package:data.table’:

    hour, isoweek, isoyear, mday, minute, month, quarter, second, wday,
    week, yday, year

The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

In [28]:
# esta funcion atributos presentes existe debido a que las modalidades poseen datasets con distinta cantidad de campos
atributos_presentes <- function( patributos )
{
  atributos <- unique( patributos )
  comun <- intersect( atributos, colnames(dataset) )

  return(  length( atributos ) == length( comun ) )
}

In [29]:
# Esta es la parte que los alumnos deben desplegar todo su ingenio
# Agregar aqui sus PROPIAS VARIABLES manuales

AgregarVariables_IntraMes <- function(dataset) {
  cat( "inicio AgregarVariables_IntraMes()\n")
  gc(verbose= FALSE)
  # INICIO de la seccion donde se deben hacer cambios con variables nuevas

  # el mes 1,2, ..12
  if( atributos_presentes( c("foto_mes") ))
    dataset[, kmes := foto_mes %% 100]

  # creo un ctr_quarter que tenga en cuenta cuando
  # los clientes hace 3 menos meses que estan
  # ya que seria injusto considerar las transacciones medidas en menor tiempo
  if( atributos_presentes( c("ctrx_quarter") ))
    dataset[, ctrx_quarter_normalizado := as.numeric(ctrx_quarter) ]

  if( atributos_presentes( c("ctrx_quarter", "cliente_antiguedad") ))
    dataset[cliente_antiguedad == 1, ctrx_quarter_normalizado := ctrx_quarter * 5]

  if( atributos_presentes( c("ctrx_quarter", "cliente_antiguedad") ))
    dataset[cliente_antiguedad == 2, ctrx_quarter_normalizado := ctrx_quarter * 2]

  if( atributos_presentes( c("ctrx_quarter", "cliente_antiguedad") ))
    dataset[
      cliente_antiguedad == 3,
      ctrx_quarter_normalizado := ctrx_quarter * 1.2
    ]

   if(atributos_presentes(c("foto_mes")))
    dataset[,foto_mes_formato_fecha := as.Date(paste(substr(dataset$foto_mes,1,4),substr(dataset$foto_mes,5,6),"01",sep='-'))]

  #dataset$foto_mes_formato_fecha <<- as.Date(paste(substr(dataset$foto_mes,1,4),substr(dataset$foto_mes,5,6),"01",sep='-'))

  if(atributos_presentes(c("cantidad_total_transacciones"))){
   auxiliarmenos1 <- dataset[,list(numero_de_cliente,foto_mes_formato_fecha, cantidad_total_transacciones)]
   auxiliarmenos2 <- dataset[,list(numero_de_cliente,foto_mes_formato_fecha,cantidad_total_transacciones)]
   # auxiliarmenos1$foto_mes_formato_fecha <- as.Date(auxiliarmenos1$foto_mes_formato_fecha)
   # auxiliarmenos2$foto_mes_formato_fecha <- as.Date(auxiliarmenos2$foto_mes_formato_fecha)
   auxiliarmenos1$foto_mes_formato_fecha <- auxiliarmenos1$foto_mes_formato_fecha  %m-%  months(1)
   auxiliarmenos2$foto_mes_formato_fecha <- auxiliarmenos2$foto_mes_formato_fecha %m-% months(2)
   auxiliarmenos1$codigo <- paste(auxiliarmenos1$numero_de_cliente,auxiliarmenos1$foto_mes_formato_fecha,sep='-')
   auxiliarmenos2$codigo <- paste(auxiliarmenos2$numero_de_cliente,auxiliarmenos2$foto_mes_formato_fecha,sep='-')

   dataset[, codigo := paste(numero_de_cliente, foto_mes_formato_fecha, sep='-') ]

   dataset[ auxiliarmenos1,
            on = "codigo",
            transaccionesmenos1 := i.cantidad_total_transacciones ]

   dataset[ auxiliarmenos2,
            on = "codigo",
            transaccionesmenos2 := i.cantidad_total_transacciones ]

   dataset[, cantidad_total_transacciones_quarter := rowSums(cbind(cantidad_total_transacciones +
    transaccionesmenos1 + transaccionesmenos2),na.rm=T) ]

   dataset[, codigo := NULL ]
   dataset[, transaccionesmenos1 := NULL ]
   dataset[, transaccionesmenos2 := NULL ]
   dataset[, foto_mes_formato_fecha := NULL ]
   rm(auxiliarmenos1)
   rm(auxiliarmenos2)
  }

  if( atributos_presentes( c("cantidad_total_transacciones_quarter") ))
    dataset[, cantidad_total_transacciones_quarter_normalizado := cantidad_total_transacciones_quarter]

  if( atributos_presentes( c("cantidad_total_transacciones_quarter", "cliente_antiguedad") ))
    dataset[cliente_antiguedad == 1, cantidad_total_transacciones_quarter_normalizado := cantidad_total_transacciones_quarter * 5]

  if( atributos_presentes( c("cantidad_total_transacciones_quarter", "cliente_antiguedad") ))
    dataset[cliente_antiguedad == 2, cantidad_total_transacciones_quarter_normalizado := cantidad_total_transacciones_quarter * 2]

  if( atributos_presentes( c("cantidad_total_transacciones_quarter", "cliente_antiguedad") ))
    dataset[cliente_antiguedad == 3, cantidad_total_transacciones_quarter_normalizado := cantidad_total_transacciones_quarter * 1.2]

  # variable extraida de una tesis de maestria de Irlanda
  if( atributos_presentes( c("mpayroll", "cliente_edad") ))
    dataset[, mpayroll_sobre_edad := mpayroll / cliente_edad]

  # se crean los nuevos campos para MasterCard  y Visa,
  #  teniendo en cuenta los NA's
  # varias formas de combinar Visa_status y Master_status
  if( atributos_presentes( c("Master_status", "Visa_status") ))
  {
    dataset[, vm_status01 := pmax(Master_status, Visa_status, na.rm = TRUE)]
    dataset[, vm_status02 := Master_status + Visa_status]

    dataset[, vm_status03 := pmax(
      ifelse(is.na(Master_status), 10, Master_status),
      ifelse(is.na(Visa_status), 10, Visa_status)
    )]

    dataset[, vm_status04 := ifelse(is.na(Master_status), 10, Master_status)
      + ifelse(is.na(Visa_status), 10, Visa_status)]

    dataset[, vm_status05 := ifelse(is.na(Master_status), 10, Master_status)
      + 100 * ifelse(is.na(Visa_status), 10, Visa_status)]

    dataset[, vm_status06 := ifelse(is.na(Visa_status),
      ifelse(is.na(Master_status), 10, Master_status),
      Visa_status
    )]

    dataset[, mv_status07 := ifelse(is.na(Master_status),
      ifelse(is.na(Visa_status), 10, Visa_status),
      Master_status
    )]
  }


  # combino MasterCard y Visa
  if( atributos_presentes( c("Master_mfinanciacion_limite", "Visa_mfinanciacion_limite") ))
    dataset[, vm_mfinanciacion_limite := rowSums(cbind(Master_mfinanciacion_limite, Visa_mfinanciacion_limite), na.rm = TRUE)]

  if( atributos_presentes( c("Master_Fvencimiento", "Visa_Fvencimiento") ))
    dataset[, vm_Fvencimiento := pmin(Master_Fvencimiento, Visa_Fvencimiento, na.rm = TRUE)]

  if( atributos_presentes( c("Master_Finiciomora", "Visa_Finiciomora") ))
    dataset[, vm_Finiciomora := pmin(Master_Finiciomora, Visa_Finiciomora, na.rm = TRUE)]

  if( atributos_presentes( c("Master_msaldototal", "Visa_msaldototal") ))
    dataset[, vm_msaldototal := rowSums(cbind(Master_msaldototal, Visa_msaldototal), na.rm = TRUE)]

  if( atributos_presentes( c("Master_msaldopesos", "Visa_msaldopesos") ))
    dataset[, vm_msaldopesos := rowSums(cbind(Master_msaldopesos, Visa_msaldopesos), na.rm = TRUE)]

  if( atributos_presentes( c("Master_msaldodolares", "Visa_msaldodolares") ))
    dataset[, vm_msaldodolares := rowSums(cbind(Master_msaldodolares, Visa_msaldodolares), na.rm = TRUE)]

  if( atributos_presentes( c("Master_mconsumospesos", "Visa_mconsumospesos") ))
    dataset[, vm_mconsumospesos := rowSums(cbind(Master_mconsumospesos, Visa_mconsumospesos), na.rm = TRUE)]

  if( atributos_presentes( c("Master_mconsumosdolares", "Visa_mconsumosdolares") ))
    dataset[, vm_mconsumosdolares := rowSums(cbind(Master_mconsumosdolares, Visa_mconsumosdolares), na.rm = TRUE)]

  if( atributos_presentes( c("Master_mlimitecompra", "Visa_mlimitecompra") ))
    dataset[, vm_mlimitecompra := rowSums(cbind(Master_mlimitecompra, Visa_mlimitecompra), na.rm = TRUE)]

  if( atributos_presentes( c("Master_madelantopesos", "Visa_madelantopesos") ))
    dataset[, vm_madelantopesos := rowSums(cbind(Master_madelantopesos, Visa_madelantopesos), na.rm = TRUE)]

  if( atributos_presentes( c("Master_madelantodolares", "Visa_madelantodolares") ))
    dataset[, vm_madelantodolares := rowSums(cbind(Master_madelantodolares, Visa_madelantodolares), na.rm = TRUE)]

  if( atributos_presentes( c("Master_fultimo_cierre", "Visa_fultimo_cierre") ))
    dataset[, vm_fultimo_cierre := pmax(Master_fultimo_cierre, Visa_fultimo_cierre, na.rm = TRUE)]

  if( atributos_presentes( c("Master_mpagado", "Visa_mpagado") ))
    dataset[, vm_mpagado := rowSums(cbind(Master_mpagado, Visa_mpagado), na.rm = TRUE)]

  if( atributos_presentes( c("Master_mpagospesos", "Visa_mpagospesos") ))
    dataset[, vm_mpagospesos := rowSums(cbind(Master_mpagospesos, Visa_mpagospesos), na.rm = TRUE)]

  if( atributos_presentes( c("Master_mpagosdolares", "Visa_mpagosdolares") ))
    dataset[, vm_mpagosdolares := rowSums(cbind(Master_mpagosdolares, Visa_mpagosdolares), na.rm = TRUE)]

  if( atributos_presentes( c("Master_fechaalta", "Visa_fechaalta") ))
    dataset[, vm_fechaalta := pmax(Master_fechaalta, Visa_fechaalta, na.rm = TRUE)]

  if( atributos_presentes( c("Master_mconsumototal", "Visa_mconsumototal") ))
    dataset[, vm_mconsumototal := rowSums(cbind(Master_mconsumototal, Visa_mconsumototal), na.rm = TRUE)]

  if( atributos_presentes( c("Master_cconsumos", "Visa_cconsumos") ))
    dataset[, vm_cconsumos := rowSums(cbind(Master_cconsumos, Visa_cconsumos), na.rm = TRUE)]

  if( atributos_presentes( c("Master_cadelantosefectivo", "Visa_cadelantosefectivo") ))
    dataset[, vm_cadelantosefectivo := rowSums(cbind(Master_cadelantosefectivo, Visa_cadelantosefectivo), na.rm = TRUE)]

  if( atributos_presentes( c("Master_mpagominimo", "Visa_mpagominimo") ))
    dataset[, vm_mpagominimo := rowSums(cbind(Master_mpagominimo, Visa_mpagominimo), na.rm = TRUE)]

  # a partir de aqui juego con la suma de Mastercard y Visa
  if( atributos_presentes( c("Master_mlimitecompra", "vm_mlimitecompra") ))
    dataset[, vmr_Master_mlimitecompra := Master_mlimitecompra / vm_mlimitecompra]

  if( atributos_presentes( c("Visa_mlimitecompra", "vm_mlimitecompra") ))
    dataset[, vmr_Visa_mlimitecompra := Visa_mlimitecompra / vm_mlimitecompra]

  if( atributos_presentes( c("vm_msaldototal", "vm_mlimitecompra") ))
    dataset[, vmr_msaldototal := vm_msaldototal / vm_mlimitecompra]

  if( atributos_presentes( c("vm_msaldopesos", "vm_mlimitecompra") ))
    dataset[, vmr_msaldopesos := vm_msaldopesos / vm_mlimitecompra]

  if( atributos_presentes( c("vm_msaldopesos", "vm_msaldototal") ))
    dataset[, vmr_msaldopesos2 := vm_msaldopesos / vm_msaldototal]

  if( atributos_presentes( c("vm_msaldodolares", "vm_mlimitecompra") ))
    dataset[, vmr_msaldodolares := vm_msaldodolares / vm_mlimitecompra]

  if( atributos_presentes( c("vm_msaldodolares", "vm_msaldototal") ))
    dataset[, vmr_msaldodolares2 := vm_msaldodolares / vm_msaldototal]

  if( atributos_presentes( c("vm_mconsumospesos", "vm_mlimitecompra") ))
    dataset[, vmr_mconsumospesos := vm_mconsumospesos / vm_mlimitecompra]

  if( atributos_presentes( c("vm_mconsumosdolares", "vm_mlimitecompra") ))
    dataset[, vmr_mconsumosdolares := vm_mconsumosdolares / vm_mlimitecompra]

  if( atributos_presentes( c("vm_madelantopesos", "vm_mlimitecompra") ))
    dataset[, vmr_madelantopesos := vm_madelantopesos / vm_mlimitecompra]

  if( atributos_presentes( c("vm_madelantodolares", "vm_mlimitecompra") ))
    dataset[, vmr_madelantodolares := vm_madelantodolares / vm_mlimitecompra]

  if( atributos_presentes( c("vm_mpagado", "vm_mlimitecompra") ))
    dataset[, vmr_mpagado := vm_mpagado / vm_mlimitecompra]

  if( atributos_presentes( c("vm_mpagospesos", "vm_mlimitecompra") ))
    dataset[, vmr_mpagospesos := vm_mpagospesos / vm_mlimitecompra]

  if( atributos_presentes( c("vm_mpagosdolares", "vm_mlimitecompra") ))
    dataset[, vmr_mpagosdolares := vm_mpagosdolares / vm_mlimitecompra]

  if( atributos_presentes( c("vm_mconsumototal", "vm_mlimitecompra") ))
    dataset[, vmr_mconsumototal := vm_mconsumototal / vm_mlimitecompra]

  if( atributos_presentes( c("vm_mpagominimo", "vm_mlimitecompra") ))
    dataset[, vmr_mpagominimo := vm_mpagominimo / vm_mlimitecompra]

  # Aqui debe usted agregar sus propias nuevas variables

  # valvula de seguridad para evitar valores infinitos
  # paso los infinitos a NULOS
  infinitos <- lapply(
    names(dataset),
    function(.name) dataset[, sum(is.infinite(get(.name)))]
  )

  infinitos_qty <- sum(unlist(infinitos))
  if (infinitos_qty > 0) {
    cat(
      "ATENCION, hay", infinitos_qty,
      "valores infinitos en tu dataset. Seran pasados a NA\n"
    )
    dataset[mapply(is.infinite, dataset)] <<- NA
  }


  # valvula de seguridad para evitar valores NaN  que es 0/0
  # paso los NaN a 0 , decision polemica si las hay
  # se invita a asignar un valor razonable segun la semantica del campo creado
  nans <- lapply(
    names(dataset),
    function(.name) dataset[, sum(is.nan(get(.name)))]
  )

  nans_qty <- sum(unlist(nans))
  if (nans_qty > 0) {
    cat(
      "ATENCION, hay", nans_qty,
      "valores NaN 0/0 en tu dataset. Seran pasados arbitrariamente a 0\n"
    )

    cat("Si no te gusta la decision, modifica a gusto el programa!\n\n")
    dataset[mapply(is.nan, dataset)] <<- 0
  }

  cat( "fin AgregarVariables_IntraMes()\n")
}

In [30]:
# agrego las variables intra mes

AgregarVariables_IntraMes(dataset)

inicio AgregarVariables_IntraMes()
fin AgregarVariables_IntraMes()

In [31]:
# visualizo las columas del dataset a esta etapa
ncol(dataset)
colnames(dataset)

[1] 171

  [1] "numero_de_cliente"
  [2] "foto_mes"
  [3] "active_quarter"
  [4] "cliente_vip"
  [5] "internet"
  [6] "cliente_edad"
  [7] "cliente_antiguedad"
  [8] "cproductos"
  [9] "tcuentas"
 [10] "ccuenta_corriente"
 [11] "ccaja_ahorro"
 [12] "cdescubierto_preacordado"
 [13] "ctarjeta_debito"
 [14] "ctarjeta_debito_transacciones"
 [15] "ctarjeta_visa"
 [16] "ctarjeta_visa_transacciones"
 [17] "ctarjeta_master"
 [18] "ctarjeta_master_transacciones"
 [19] "cprestamos_personales"
 [20] "cprestamos_prendarios"
 [21] "cprestamos_hipotecarios"
 [22] "cplazo_fijo"
 [23] "cinversion1"
 [24] "cinversion2"
 [25] "cseguro_vida"
 [26] "cseguro_auto"
 [27] "cseguro_vivienda"
 [28] "cseguro_accidentes_personales"
 [29] "ccaja_seguridad"
 [30] "cpayroll_trx"
 [31] "cpayroll2_trx"
 [32] "ccuenta_debitos_automaticos"
 [33] "ctarjeta_visa_debitos_automaticos"
 [34] "ctarjeta_master_debitos_automaticos"
 [35] "cpagodeservicios"
 [36] "cpagomiscuentas"
 [37] "ccajeros_propios_descuentos"
 [38] "ctarjeta_visa_descuentos"
 [39] "ctarjeta_master_descuentos"
 [40] "ccomisiones_mantenimiento"
 [41] "ccomisiones_otras"
 [42] "cforex"
 [43] "cforex_buy"
 [44] "cforex_sell"
 [45] "ctransferencias_recibidas"
 [46] "ctransferencias_emitidas"
 [47] "cextraccion_autoservicio"
 [48] "ccheques_depositados"
 [49] "ccheques_emitidos"
 [50] "ccheques_depositados_rechazados"
 [51] "ccheques_emitidos_rechazados"
 [52] "tcallcenter"
 [53] "ccallcenter_transacciones"
 [54] "thomebanking"
 [55] "chomebanking_transacciones"
 [56] "ccajas_transacciones"
 [57] "ccajas_consultas"
 [58] "ccajas_depositos"
 [59] "ccajas_extracciones"
 [60] "ccajas_otras"
 [61] "catm_trx"
 [62] "catm_trx_other"
 [63] "ctrx_quarter"
 [64] "tmobile_app"
 [65] "cmobile_app_trx"
 [66] "Master_delinquency"
 [67] "Master_status"
 [68] "Master_Fvencimiento"
 [69] "Master_Finiciomora"
 [70] "Master_fultimo_cierre"
 [71] "Master_fechaalta"
 [72] "Master_cconsumos"
 [73] "Master_cadelantosefectivo"
 [74] "Visa_delinquency"
 [75] "Visa_status"
 [76] "Visa_Fvencimiento"
 [77] "Visa_Finiciomora"
 [78] "Visa_fultimo_cierre"
 [79] "Visa_fechaalta"
 [80] "Visa_cconsumos"
 [81] "Visa_cadelantosefectivo"
 [82] "clase_ternaria"
 [83] "mrentabilidad_rank"
 [84] "mrentabilidad_annual_rank"
 [85] "mcomisiones_rank"
 [86] "mactivos_margen_rank"
 [87] "mpasivos_margen_rank"
 [88] "mcuenta_corriente_adicional_rank"
 [89] "mcuenta_corriente_rank"
 [90] "mcaja_ahorro_rank"
 [91] "mcaja_ahorro_adicional_rank"
 [92] "mcaja_ahorro_dolares_rank"
 [93] "mcuentas_saldo_rank"
 [94] "mautoservicio_rank"
 [95] "mtarjeta_visa_consumo_rank"
 [96] "mtarjeta_master_consumo_rank"
 [97] "mprestamos_personales_rank"
 [98] "mprestamos_prendarios_rank"
 [99] "mprestamos_hipotecarios_rank"
[100] "mplazo_fijo_dolares_rank"
[101] "mplazo_fijo_pesos_rank"
[102] "minversion1_pesos_rank"
[103] "minversion1_dolares_rank"
[104] "minversion2_rank"
[105] "mpayroll_rank"
[106] "mpayroll2_rank"
[107] "mcuenta_debitos_automaticos_rank"
[108] "mttarjeta_visa_debitos_automaticos_rank"
[109] "mttarjeta_master_debitos_automaticos_rank"
[110] "mpagodeservicios_rank"
[111] "mpagomiscuentas_rank"
[112] "mcajeros_propios_descuentos_rank"
[113] "mtarjeta_visa_descuentos_rank"
[114] "mtarjeta_master_descuentos_rank"
[115] "mcomisiones_mantenimiento_rank"
[116] "mcomisiones_otras_rank"
[117] "mforex_buy_rank"
[118] "mforex_sell_rank"
[119] "mtransferencias_recibidas_rank"
[120] "mtransferencias_emitidas_rank"
[121] "mextraccion_autoservicio_rank"
[122] "mcheques_depositados_rank"
[123] "mcheques_emitidos_rank"
[124] "mcheques_depositados_rechazados_rank"
[125] "mcheques_emitidos_rechazados_rank"
[126] "matm_rank"
[127] "matm_other_rank"
[128] "Master_mfinanciacion_limite_rank"
[129] "Master_msaldototal_rank"
[130] "Master_msaldopesos_rank"
[131] "Master_msaldodolares_rank"
[132] "Master_mconsumospesos_rank"
[133] "Master_mconsumosdolares_rank"
[134] "Master_mlimitecompra_rank"
[135] "Master_madelantopesos_rank"
[136] "Master_madelantodolares_rank"
[137] "Master_mpagado_rank"
[138] "Master_mpagospesos_rank"
[139] "Master_mpagosdolares_rank"
[140] "Master_mconsumototal_rank"
[141] "Master_mpagominimo_rank"
[142] "Visa_mfinanciacion_limite_rank"
[143] "Visa_msaldototal_rank"
[144] "Visa_msaldopesos_rank"
[145] "Visa_msaldodolares_rank"
[146] "Visa_mconsumospesos_rank"
[147] "Visa_mconsumosdolares_rank"
[148] "Visa_mlimitecompra_rank"
[149] "Visa_madelantopesos_rank"
[150] "Visa_madelantodolares_rank"
[151] "Visa_mpagado_rank"
[152] "Visa_mpagospesos_rank"
[153] "Visa_mpagosdolares_rank"
[154] "Visa_mconsumototal_rank"
[155] "Visa_mpagominimo_rank"
[156] "kmes"
[157] "ctrx_quarter_normalizado"
[158] "foto_mes_formato_fecha"
[159] "vm_status01"
[160] "vm_status02"
[161] "vm_status03"
[162] "vm_status04"
[163] "vm_status05"
[164] "vm_status06"
[165] "mv_status07"
[166] "vm_Fvencimiento"
[167] "vm_Finiciomora"
[168] "vm_fultimo_cierre"
[169] "vm_fechaalta"
[170] "vm_cconsumos"
[171] "vm_cadelantosefectivo"

#### 9.7.1.4  FEhist Feature Engineering historico

El Feature Engineering Histórico es la etapa que más aporta a la ganancia final, ya que enriquece cada registro del dataset con su historia.

Para cada campo del dataset original (*)
se crean lo siguientes campos de a partir de la historia
* lag1  lags de orden 1
* delta1  =  valor actual - lag1
* lag2  lags de orden 2
* delta2  = valor actual - lag2


(*) Excepto para los campos  <numero_de_cliente,  foto_mes,  clase_ternaria>

In [32]:
if( !require("Rcpp")) install.packages("Rcpp", repos = "http://cran.us.r-project.org")
require("Rcpp")

Loading required package: Rcpp

In [33]:
# se calculan para los 6 meses previos el minimo, maximo y
#  tendencia calculada con cuadrados minimos
# la formula de calculo de la tendencia puede verse en
#  https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Book%3A_Introductory_Statistics_(Shafer_and_Zhang)/10%3A_Correlation_and_Regression/10.04%3A_The_Least_Squares_Regression_Line
# para la maxíma velocidad esta funcion esta escrita en lenguaje C,
# y no en la porqueria de R o Python

cppFunction("NumericVector fhistC(NumericVector pcolumna, IntegerVector pdesde )
{
  /* Aqui se cargan los valores para la regresion */
  double  x[100] ;
  double  y[100] ;

  int n = pcolumna.size();
  NumericVector out( 5*n );

  for(int i = 0; i < n; i++)
  {
    //lag
    if( pdesde[i]-1 < i )  out[ i + 4*n ]  =  pcolumna[i-1] ;
    else                   out[ i + 4*n ]  =  NA_REAL ;


    int  libre    = 0 ;
    int  xvalor   = 1 ;

    for( int j= pdesde[i]-1;  j<=i; j++ )
    {
       double a = pcolumna[j] ;

       if( !R_IsNA( a ) )
       {
          y[ libre ]= a ;
          x[ libre ]= xvalor ;
          libre++ ;
       }

       xvalor++ ;
    }

    /* Si hay al menos dos valores */
    if( libre > 1 )
    {
      double  xsum  = x[0] ;
      double  ysum  = y[0] ;
      double  xysum = xsum * ysum ;
      double  xxsum = xsum * xsum ;
      double  vmin  = y[0] ;
      double  vmax  = y[0] ;

      for( int h=1; h<libre; h++)
      {
        xsum  += x[h] ;
        ysum  += y[h] ;
        xysum += x[h]*y[h] ;
        xxsum += x[h]*x[h] ;

        if( y[h] < vmin )  vmin = y[h] ;
        if( y[h] > vmax )  vmax = y[h] ;
      }

      out[ i ]  =  (libre*xysum - xsum*ysum)/(libre*xxsum -xsum*xsum) ;
      out[ i + n ]    =  vmin ;
      out[ i + 2*n ]  =  vmax ;
      out[ i + 3*n ]  =  ysum / libre ;
    }
    else
    {
      out[ i       ]  =  NA_REAL ;
      out[ i + n   ]  =  NA_REAL ;
      out[ i + 2*n ]  =  NA_REAL ;
      out[ i + 3*n ]  =  NA_REAL ;
    }
  }

  return  out;
}")

In [34]:
# calcula la tendencia de las variables cols de los ultimos 6 meses
# la tendencia es la pendiente de la recta que ajusta por cuadrados minimos
# La funcionalidad de ratioavg es autoria de  Daiana Sparta,  UAustral  2021

TendenciaYmuchomas <- function(
    dataset, cols, ventana = 6, tendencia = TRUE,
    minimo = TRUE, maximo = TRUE, promedio = TRUE,
    ratioavg = FALSE, ratiomax = FALSE) {
  gc(verbose= FALSE)
  # Esta es la cantidad de meses que utilizo para la historia
  ventana_regresion <- ventana

  last <- nrow(dataset)

  # creo el vector_desde que indica cada ventana
  # de esta forma se acelera el procesamiento ya que lo hago una sola vez
  vector_ids <- dataset[ , numero_de_cliente ]

  vector_desde <- seq(
    -ventana_regresion + 2,
    nrow(dataset) - ventana_regresion + 1
  )

  vector_desde[1:ventana_regresion] <- 1

  for (i in 2:last) {
    if (vector_ids[i - 1] != vector_ids[i]) {
      vector_desde[i] <- i
    }
  }
  for (i in 2:last) {
    if (vector_desde[i] < vector_desde[i - 1]) {
      vector_desde[i] <- vector_desde[i - 1]
    }
  }

  for (campo in cols) {
    nueva_col <- fhistC(dataset[, get(campo)], vector_desde)

    if (tendencia) {
      dataset[, paste0(campo, "_tend", ventana) :=
        nueva_col[(0 * last + 1):(1 * last)]]
    }

    if (minimo) {
      dataset[, paste0(campo, "_min", ventana) :=
        nueva_col[(1 * last + 1):(2 * last)]]
    }

    if (maximo) {
      dataset[, paste0(campo, "_max", ventana) :=
        nueva_col[(2 * last + 1):(3 * last)]]
    }

    if (promedio) {
      dataset[, paste0(campo, "_avg", ventana) :=
        nueva_col[(3 * last + 1):(4 * last)]]
    }

    if (ratioavg) {
      dataset[, paste0(campo, "_ratioavg", ventana) :=
        get(campo) / nueva_col[(3 * last + 1):(4 * last)]]
    }

    if (ratiomax) {
      dataset[, paste0(campo, "_ratiomax", ventana) :=
        get(campo) / nueva_col[(2 * last + 1):(3 * last)]]
    }
  }
}

In [35]:
# Feature Engineering Historico

setorder(dataset, numero_de_cliente, foto_mes)

# todo es lagueable, menos la primary key y la clase
cols_lagueables <- copy( setdiff(
    colnames(dataset),
    c("numero_de_cliente", "foto_mes", "clase_ternaria")
) )

# https://rdrr.io/cran/data.table/man/shift.html

# lags de orden 1
dataset[,
    paste0(cols_lagueables, "_lag1") := shift(.SD, 1, NA, "lag"),
    by = numero_de_cliente,
    .SDcols = cols_lagueables
]

# lags de orden 2
dataset[,
    paste0(cols_lagueables, "_lag2") := shift(.SD, 2, NA, "lag"),
    by = numero_de_cliente,
    .SDcols = cols_lagueables
]

# agrego los delta lags
for (vcol in cols_lagueables)
{
    dataset[, paste0(vcol, "_delta1") := get(vcol) - get(paste0(vcol, "_lag1"))]
    dataset[, paste0(vcol, "_delta2") := get(vcol) - get(paste0(vcol, "_lag2"))]
}

In [36]:
# parametros de Feature Engineering Historico de Tendencias
PARAM$FE_hist$Tendencias$run <- TRUE
PARAM$FE_hist$Tendencias$ventana <- 6
PARAM$FE_hist$Tendencias$tendencia <- TRUE
PARAM$FE_hist$Tendencias$minimo <- FALSE
PARAM$FE_hist$Tendencias$maximo <- FALSE
PARAM$FE_hist$Tendencias$promedio <- FALSE
PARAM$FE_hist$Tendencias$ratioavg <- FALSE
PARAM$FE_hist$Tendencias$ratiomax <- FALSE

In [37]:
cols_lagueables <- intersect(cols_lagueables, colnames(dataset))
setorder(dataset, numero_de_cliente, foto_mes)

if( PARAM$FE_hist$Tendencias$run) {
    TendenciaYmuchomas(dataset,
    cols = cols_lagueables,
    ventana = PARAM$FE_hist$Tendencias$ventana, # 6 meses de historia
    tendencia = PARAM$FE_hist$Tendencias$tendencia,
    minimo = PARAM$FE_hist$Tendencias$minimo,
    maximo = PARAM$FE_hist$Tendencias$maximo,
    promedio = PARAM$FE_hist$Tendencias$promedio,
    ratioavg = PARAM$FE_hist$Tendencias$ratioavg,
    ratiomax = PARAM$FE_hist$Tendencias$ratiomax
  )
}

Verificacion de los campos recien creados

In [38]:
ncol(dataset)
colnames(dataset)

[1] 1011

   [1] "numero_de_cliente"
   [2] "foto_mes"
   [3] "active_quarter"
   [4] "cliente_vip"
   [5] "internet"
   [6] "cliente_edad"
   [7] "cliente_antiguedad"
   [8] "cproductos"
   [9] "tcuentas"
  [10] "ccuenta_corriente"
  [11] "ccaja_ahorro"
  [12] "cdescubierto_preacordado"
  [13] "ctarjeta_debito"
  [14] "ctarjeta_debito_transacciones"
  [15] "ctarjeta_visa"
  [16] "ctarjeta_visa_transacciones"
  [17] "ctarjeta_master"
  [18] "ctarjeta_master_transacciones"
  [19] "cprestamos_personales"
  [20] "cprestamos_prendarios"
  [21] "cprestamos_hipotecarios"
  [22] "cplazo_fijo"
  [23] "cinversion1"
  [24] "cinversion2"
  [25] "cseguro_vida"
  [26] "cseguro_auto"
  [27] "cseguro_vivienda"
  [28] "cseguro_accidentes_personales"
  [29] "ccaja_seguridad"
  [30] "cpayroll_trx"
  [31] "cpayroll2_trx"
  [32] "ccuenta_debitos_automaticos"
  [33] "ctarjeta_visa_debitos_automaticos"
  [34] "ctarjeta_master_debitos_automaticos"
  [35] "cpagodeservicios"
  [36] "cpagomiscuentas"
  [37] "ccajeros_propios_descuentos"
  [38] "ctarjeta_visa_descuentos"
  [39] "ctarjeta_master_descuentos"
  [40] "ccomisiones_mantenimiento"
  [41] "ccomisiones_otras"
  [42] "cforex"
  [43] "cforex_buy"
  [44] "cforex_sell"
  [45] "ctransferencias_recibidas"
  [46] "ctransferencias_emitidas"
  [47] "cextraccion_autoservicio"
  [48] "ccheques_depositados"
  [49] "ccheques_emitidos"
  [50] "ccheques_depositados_rechazados"
  [51] "ccheques_emitidos_rechazados"
  [52] "tcallcenter"
  [53] "ccallcenter_transacciones"
  [54] "thomebanking"
  [55] "chomebanking_transacciones"
  [56] "ccajas_transacciones"
  [57] "ccajas_consultas"
  [58] "ccajas_depositos"
  [59] "ccajas_extracciones"
  [60] "ccajas_otras"
  [61] "catm_trx"
  [62] "catm_trx_other"
  [63] "ctrx_quarter"
  [64] "tmobile_app"
  [65] "cmobile_app_trx"
  [66] "Master_delinquency"
  [67] "Master_status"
  [68] "Master_Fvencimiento"
  [69] "Master_Finiciomora"
  [70] "Master_fultimo_cierre"
  [71] "Master_fechaalta"
  [72] "Master_cconsumos"
  [73] "Master_cadelantosefectivo"
  [74] "Visa_delinquency"
  [75] "Visa_status"
  [76] "Visa_Fvencimiento"
  [77] "Visa_Finiciomora"
  [78] "Visa_fultimo_cierre"
  [79] "Visa_fechaalta"
  [80] "Visa_cconsumos"
  [81] "Visa_cadelantosefectivo"
  [82] "clase_ternaria"
  [83] "mrentabilidad_rank"
  [84] "mrentabilidad_annual_rank"
  [85] "mcomisiones_rank"
  [86] "mactivos_margen_rank"
  [87] "mpasivos_margen_rank"
  [88] "mcuenta_corriente_adicional_rank"
  [89] "mcuenta_corriente_rank"
  [90] "mcaja_ahorro_rank"
  [91] "mcaja_ahorro_adicional_rank"
  [92] "mcaja_ahorro_dolares_rank"
  [93] "mcuentas_saldo_rank"
  [94] "mautoservicio_rank"
  [95] "mtarjeta_visa_consumo_rank"
  [96] "mtarjeta_master_consumo_rank"
  [97] "mprestamos_personales_rank"
  [98] "mprestamos_prendarios_rank"
  [99] "mprestamos_hipotecarios_rank"
 [100] "mplazo_fijo_dolares_rank"
 [101] "mplazo_fijo_pesos_rank"
 [102] "minversion1_pesos_rank"
 [103] "minversion1_dolares_rank"
 [104] "minversion2_rank"
 [105] "mpayroll_rank"
 [106] "mpayroll2_rank"
 [107] "mcuenta_debitos_automaticos_rank"
 [108] "mttarjeta_visa_debitos_automaticos_rank"
 [109] "mttarjeta_master_debitos_automaticos_rank"
 [110] "mpagodeservicios_rank"
 [111] "mpagomiscuentas_rank"
 [112] "mcajeros_propios_descuentos_rank"
 [113] "mtarjeta_visa_descuentos_rank"
 [114] "mtarjeta_master_descuentos_rank"
 [115] "mcomisiones_mantenimiento_rank"
 [116] "mcomisiones_otras_rank"
 [117] "mforex_buy_rank"
 [118] "mforex_sell_rank"
 [119] "mtransferencias_recibidas_rank"
 [120] "mtransferencias_emitidas_rank"
 [121] "mextraccion_autoservicio_rank"
 [122] "mcheques_depositados_rank"
 [123] "mcheques_emitidos_rank"
 [124] "mcheques_depositados_rechazados_rank"
 [125] "mcheques_emitidos_rechazados_rank"
 [126] "matm_rank"
 [127] "matm_other_rank"
 [128] "Master_mfinanciacion_limite_rank"
 [129] "Master_msaldototal_rank"
 [130] "Master_msaldopesos_rank"
 [131] "Master_msaldodolares_rank"
 [132] "Master_mconsumospesos_rank"
 [133] "Master_mconsumosdolares_rank"
 [134] "Master_mlimitecompra_rank"
 [135] "Master_madelantopesos_rank"
 [136] "Master_madelantodolares_rank"
 [137] "Master_mpagado_rank"
 [138] "Master_mpagospesos_rank"
 [139] "Master_mpagosdolares_rank"
 [140] "Master_mconsumototal_rank"
 [141] "Master_mpagominimo_rank"
 [142] "Visa_mfinanciacion_limite_rank"
 [143] "Visa_msaldototal_rank"
 [144] "Visa_msaldopesos_rank"
 [145] "Visa_msaldodolares_rank"
 [146] "Visa_mconsumospesos_rank"
 [147] "Visa_mconsumosdolares_rank"
 [148] "Visa_mlimitecompra_rank"
 [149] "Visa_madelantopesos_rank"
 [150] "Visa_madelantodolares_rank"
 [151] "Visa_mpagado_rank"
 [152] "Visa_mpagospesos_rank"
 [153] "Visa_mpagosdolares_rank"
 [154] "Visa_mconsumototal_rank"
 [155] "Visa_mpagominimo_rank"
 [156] "kmes"
 [157] "ctrx_quarter_normalizado"
 [158] "foto_mes_formato_fecha"
 [159] "vm_status01"
 [160] "vm_status02"
 [161] "vm_status03"
 [162] "vm_status04"
 [163] "vm_status05"
 [164] "vm_status06"
 [165] "mv_status07"
 [166] "vm_Fvencimiento"
 [167] "vm_Finiciomora"
 [168] "vm_fultimo_cierre"
 [169] "vm_fechaalta"
 [170] "vm_cconsumos"
 [171] "vm_cadelantosefectivo"
 [172] "active_quarter_lag1"
 [173] "cliente_vip_lag1"
 [174] "internet_lag1"
 [175] "cliente_edad_lag1"
 [176] "cliente_antiguedad_lag1"
 [177] "cproductos_lag1"
 [178] "tcuentas_lag1"
 [179] "ccuenta_corriente_lag1"
 [180] "ccaja_ahorro_lag1"
 [181] "cdescubierto_preacordado_lag1"
 [182] "ctarjeta_debito_lag1"
 [183] "ctarjeta_debito_transacciones_lag1"
 [184] "ctarjeta_visa_lag1"
 [185] "ctarjeta_visa_transacciones_lag1"
 [186] "ctarjeta_master_lag1"
 [187] "ctarjeta_master_transacciones_lag1"
 [188] "cprestamos_personales_lag1"
 [189] "cprestamos_prendarios_lag1"
 [190] "cprestamos_hipotecarios_lag1"
 [191] "cplazo_fijo_lag1"
 [192] "cinversion1_lag1"
 [193] "cinversion2_lag1"
 [194] "cseguro_vida_lag1"
 [195] "cseguro_auto_lag1"
 [196] "cseguro_vivienda_lag1"
 [197] "cseguro_accidentes_personales_lag1"
 [198] "ccaja_seguridad_lag1"
 [199] "cpayroll_trx_lag1"
 [200] "cpayroll2_trx_lag1"
 [201] "ccuenta_debitos_automaticos_lag1"
 [202] "ctarjeta_visa_debitos_automaticos_lag1"
 [203] "ctarjeta_master_debitos_automaticos_lag1"
 [204] "cpagodeservicios_lag1"
 [205] "cpagomiscuentas_lag1"
 [206] "ccajeros_propios_descuentos_lag1"
 [207] "ctarjeta_visa_descuentos_lag1"
 [208] "ctarjeta_master_descuentos_lag1"
 [209] "ccomisiones_mantenimiento_lag1"
 [210] "ccomisiones_otras_lag1"
 [211] "cforex_lag1"
 [212] "cforex_buy_lag1"
 [213] "cforex_sell_lag1"
 [214] "ctransferencias_recibidas_lag1"
 [215] "ctransferencias_emitidas_lag1"
 [216] "cextraccion_autoservicio_lag1"
 [217] "ccheques_depositados_lag1"
 [218] "ccheques_emitidos_lag1"
 [219] "ccheques_depositados_rechazados_lag1"
 [220] "ccheques_emitidos_rechazados_lag1"
 [221] "tcallcenter_lag1"
 [222] "ccallcenter_transacciones_lag1"
 [223] "thomebanking_lag1"
 [224] "chomebanking_transacciones_lag1"
 [225] "ccajas_transacciones_lag1"
 [226] "ccajas_consultas_lag1"
 [227] "ccajas_depositos_lag1"
 [228] "ccajas_extracciones_lag1"
 [229] "ccajas_otras_lag1"
 [230] "catm_trx_lag1"
 [231] "catm_trx_other_lag1"
 [232] "ctrx_quarter_lag1"
 [233] "tmobile_app_lag1"
 [234] "cmobile_app_trx_lag1"
 [235] "Master_delinquency_lag1"
 [236] "Master_status_lag1"
 [237] "Master_Fvencimiento_lag1"
 [238] "Master_Finiciomora_lag1"
 [239] "Master_fultimo_cierre_lag1"
 [240] "Master_fechaalta_lag1"
 [241] "Master_cconsumos_lag1"
 [242] "Master_cadelantosefectivo_lag1"
 [243] "Visa_delinquency_lag1"
 [244] "Visa_status_lag1"
 [245] "Visa_Fvencimiento_lag1"
 [246] "Visa_Finiciomora_lag1"
 [247] "Visa_fultimo_cierre_lag1"
 [248] "Visa_fechaalta_lag1"
 [249] "Visa_cconsumos_lag1"
 [250] "Visa_cadelantosefectivo_lag1"
 [251] "mrentabilidad_rank_lag1"
 [252] "mrentabilidad_annual_rank_lag1"
 [253] "mcomisiones_rank_lag1"
 [254] "mactivos_margen_rank_lag1"
 [255] "mpasivos_margen_rank_lag1"
 [256] "mcuenta_corriente_adicional_rank_lag1"
 [257] "mcuenta_corriente_rank_lag1"
 [258] "mcaja_ahorro_rank_lag1"
 [259] "mcaja_ahorro_adicional_rank_lag1"
 [260] "mcaja_ahorro_dolares_rank_lag1"
 [261] "mcuentas_saldo_rank_lag1"
 [262] "mautoservicio_rank_lag1"
 [263] "mtarjeta_visa_consumo_rank_lag1"
 [264] "mtarjeta_master_consumo_rank_lag1"
 [265] "mprestamos_personales_rank_lag1"
 [266] "mprestamos_prendarios_rank_lag1"
 [267] "mprestamos_hipotecarios_rank_lag1"
 [268] "mplazo_fijo_dolares_rank_lag1"
 [269] "mplazo_fijo_pesos_rank_lag1"
 [270] "minversion1_pesos_rank_lag1"
 [271] "minversion1_dolares_rank_lag1"
 [272] "minversion2_rank_lag1"
 [273] "mpayroll_rank_lag1"
 [274] "mpayroll2_rank_lag1"
 [275] "mcuenta_debitos_automaticos_rank_lag1"
 [276] "mttarjeta_visa_debitos_automaticos_rank_lag1"
 [277] "mttarjeta_master_debitos_automaticos_rank_lag1"
 [278] "mpagodeservicios_rank_lag1"
 [279] "mpagomiscuentas_rank_lag1"
 [280] "mcajeros_propios_descuentos_rank_lag1"
 [281] "mtarjeta_visa_descuentos_rank_lag1"
 [282] "mtarjeta_master_descuentos_rank_lag1"
 [283] "mcomisiones_mantenimiento_rank_lag1"
 [284] "mcomisiones_otras_rank_lag1"
 [285] "mforex_buy_rank_lag1"
 [286] "mforex_sell_rank_lag1"
 [287] "mtransferencias_recibidas_rank_lag1"
 [288] "mtransferencias_emitidas_rank_lag1"
 [289] "mextraccion_autoservicio_rank_lag1"
 [290] "mcheques_depositados_rank_lag1"
 [291] "mcheques_emitidos_rank_lag1"
 [292] "mcheques_depositados_rechazados_rank_lag1"
 [293] "mcheques_emitidos_rechazados_rank_lag1"
 [294] "matm_rank_lag1"
 [295] "matm_other_rank_lag1"
 [296] "Master_mfinanciacion_limite_rank_lag1"
 [297] "Master_msaldototal_rank_lag1"
 [298] "Master_msaldopesos_rank_lag1"
 [299] "Master_msaldodolares_rank_lag1"
 [300] "Master_mconsumospesos_rank_lag1"
 [301] "Master_mconsumosdolares_rank_lag1"
 [302] "Master_mlimitecompra_rank_lag1"
 [303] "Master_madelantopesos_rank_lag1"
 [304] "Master_madelantodolares_rank_lag1"
 [305] "Master_mpagado_rank_lag1"
 [306] "Master_mpagospesos_rank_lag1"
 [307] "Master_mpagosdolares_rank_lag1"
 [308] "Master_mconsumototal_rank_lag1"
 [309] "Master_mpagominimo_rank_lag1"
 [310] "Visa_mfinanciacion_limite_rank_lag1"
 [311] "Visa_msaldototal_rank_lag1"
 [312] "Visa_msaldopesos_rank_lag1"
 [313] "Visa_msaldodolares_rank_lag1"
 [314] "Visa_mconsumospesos_rank_lag1"
 [315] "Visa_mconsumosdolares_rank_lag1"
 [316] "Visa_mlimitecompra_rank_lag1"
 [317] "Visa_madelantopesos_rank_lag1"
 [318] "Visa_madelantodolares_rank_lag1"
 [319] "Visa_mpagado_rank_lag1"
 [320] "Visa_mpagospesos_rank_lag1"
 [321] "Visa_mpagosdolares_rank_lag1"
 [322] "Visa_mconsumototal_rank_lag1"
 [323] "Visa_mpagominimo_rank_lag1"
 [324] "kmes_lag1"
 [325] "ctrx_quarter_normalizado_lag1"
 [326] "foto_mes_formato_fecha_lag1"
 [327] "vm_status01_lag1"
 [328] "vm_status02_lag1"
 [329] "vm_status03_lag1"
 [330] "vm_status04_lag1"
 [331] "vm_status05_lag1"
 [332] "vm_status06_lag1"
 [333] "mv_status07_lag1"
 [334] "vm_Fvencimiento_lag1"
 [335] "vm_Finiciomora_lag1"
 [336] "vm_fultimo_cierre_lag1"
 [337] "vm_fechaalta_lag1"
 [338] "vm_cconsumos_lag1"
 [339] "vm_cadelantosefectivo_lag1"
 [340] "active_quarter_lag2"
 [341] "cliente_vip_lag2"
 [342] "internet_lag2"
 [343] "cliente_edad_lag2"
 [344] "cliente_antiguedad_lag2"
 [345] "cproductos_lag2"
 [346] "tcuentas_lag2"
 [347] "ccuenta_corriente_lag2"
 [348] "ccaja_ahorro_lag2"
 [349] "cdescubierto_preacordado_lag2"
 [350] "ctarjeta_debito_lag2"
 [351] "ctarjeta_debito_transacciones_lag2"
 [352] "ctarjeta_visa_lag2"
 [353] "ctarjeta_visa_transacciones_lag2"
 [354] "ctarjeta_master_lag2"
 [355] "ctarjeta_master_transacciones_lag2"
 [356] "cprestamos_personales_lag2"
 [357] "cprestamos_prendarios_lag2"
 [358] "cprestamos_hipotecarios_lag2"
 [359] "cplazo_fijo_lag2"
 [360] "cinversion1_lag2"
 [361] "cinversion2_lag2"
 [362] "cseguro_vida_lag2"
 [363] "cseguro_auto_lag2"
 [364] "cseguro_vivienda_lag2"
 [365] "cseguro_accidentes_personales_lag2"
 [366] "ccaja_seguridad_lag2"
 [367] "cpayroll_trx_lag2"
 [368] "cpayroll2_trx_lag2"
 [369] "ccuenta_debitos_automaticos_lag2"
 [370] "ctarjeta_visa_debitos_automaticos_lag2"
 [371] "ctarjeta_master_debitos_automaticos_lag2"
 [372] "cpagodeservicios_lag2"
 [373] "cpagomiscuentas_lag2"
 [374] "ccajeros_propios_descuentos_lag2"
 [375] "ctarjeta_visa_descuentos_lag2"
 [376] "ctarjeta_master_descuentos_lag2"
 [377] "ccomisiones_mantenimiento_lag2"
 [378] "ccomisiones_otras_lag2"
 [379] "cforex_lag2"
 [380] "cforex_buy_lag2"
 [381] "cforex_sell_lag2"
 [382] "ctransferencias_recibidas_lag2"
 [383] "ctransferencias_emitidas_lag2"
 [384] "cextraccion_autoservicio_lag2"
 [385] "ccheques_depositados_lag2"
 [386] "ccheques_emitidos_lag2"
 [387] "ccheques_depositados_rechazados_lag2"
 [388] "ccheques_emitidos_rechazados_lag2"
 [389] "tcallcenter_lag2"
 [390] "ccallcenter_transacciones_lag2"
 [391] "thomebanking_lag2"
 [392] "chomebanking_transacciones_lag2"
 [393] "ccajas_transacciones_lag2"
 [394] "ccajas_consultas_lag2"
 [395] "ccajas_depositos_lag2"
 [396] "ccajas_extracciones_lag2"
 [397] "ccajas_otras_lag2"
 [398] "catm_trx_lag2"
 [399] "catm_trx_other_lag2"
 [400] "ctrx_quarter_lag2"
 [401] "tmobile_app_lag2"
 [402] "cmobile_app_trx_lag2"
 [403] "Master_delinquency_lag2"
 [404] "Master_status_lag2"
 [405] "Master_Fvencimiento_lag2"
 [406] "Master_Finiciomora_lag2"
 [407] "Master_fultimo_cierre_lag2"
 [408] "Master_fechaalta_lag2"
 [409] "Master_cconsumos_lag2"
 [410] "Master_cadelantosefectivo_lag2"
 [411] "Visa_delinquency_lag2"
 [412] "Visa_status_lag2"
 [413] "Visa_Fvencimiento_lag2"
 [414] "Visa_Finiciomora_lag2"
 [415] "Visa_fultimo_cierre_lag2"
 [416] "Visa_fechaalta_lag2"
 [417] "Visa_cconsumos_lag2"
 [418] "Visa_cadelantosefectivo_lag2"
 [419] "mrentabilidad_rank_lag2"
 [420] "mrentabilidad_annual_rank_lag2"
 [421] "mcomisiones_rank_lag2"
 [422] "mactivos_margen_rank_lag2"
 [423] "mpasivos_margen_rank_lag2"
 [424] "mcuenta_corriente_adicional_rank_lag2"
 [425] "mcuenta_corriente_rank_lag2"
 [426] "mcaja_ahorro_rank_lag2"
 [427] "mcaja_ahorro_adicional_rank_lag2"
 [428] "mcaja_ahorro_dolares_rank_lag2"
 [429] "mcuentas_saldo_rank_lag2"
 [430] "mautoservicio_rank_lag2"
 [431] "mtarjeta_visa_consumo_rank_lag2"
 [432] "mtarjeta_master_consumo_rank_lag2"
 [433] "mprestamos_personales_rank_lag2"
 [434] "mprestamos_prendarios_rank_lag2"
 [435] "mprestamos_hipotecarios_rank_lag2"
 [436] "mplazo_fijo_dolares_rank_lag2"
 [437] "mplazo_fijo_pesos_rank_lag2"
 [438] "minversion1_pesos_rank_lag2"
 [439] "minversion1_dolares_rank_lag2"
 [440] "minversion2_rank_lag2"
 [441] "mpayroll_rank_lag2"
 [442] "mpayroll2_rank_lag2"
 [443] "mcuenta_debitos_automaticos_rank_lag2"
 [444] "mttarjeta_visa_debitos_automaticos_rank_lag2"
 [445] "mttarjeta_master_debitos_automaticos_rank_lag2"
 [446] "mpagodeservicios_rank_lag2"
 [447] "mpagomiscuentas_rank_lag2"
 [448] "mcajeros_propios_descuentos_rank_lag2"
 [449] "mtarjeta_visa_descuentos_rank_lag2"
 [450] "mtarjeta_master_descuentos_rank_lag2"
 [451] "mcomisiones_mantenimiento_rank_lag2"
 [452] "mcomisiones_otras_rank_lag2"
 [453] "mforex_buy_rank_lag2"
 [454] "mforex_sell_rank_lag2"
 [455] "mtransferencias_recibidas_rank_lag2"
 [456] "mtransferencias_emitidas_rank_lag2"
 [457] "mextraccion_autoservicio_rank_lag2"
 [458] "mcheques_depositados_rank_lag2"
 [459] "mcheques_emitidos_rank_lag2"
 [460] "mcheques_depositados_rechazados_rank_lag2"
 [461] "mcheques_emitidos_rechazados_rank_lag2"
 [462] "matm_rank_lag2"
 [463] "matm_other_rank_lag2"
 [464] "Master_mfinanciacion_limite_rank_lag2"
 [465] "Master_msaldototal_rank_lag2"
 [466] "Master_msaldopesos_rank_lag2"
 [467] "Master_msaldodolares_rank_lag2"
 [468] "Master_mconsumospesos_rank_lag2"
 [469] "Master_mconsumosdolares_rank_lag2"
 [470] "Master_mlimitecompra_rank_lag2"
 [471] "Master_madelantopesos_rank_lag2"
 [472] "Master_madelantodolares_rank_lag2"
 [473] "Master_mpagado_rank_lag2"
 [474] "Master_mpagospesos_rank_lag2"
 [475] "Master_mpagosdolares_rank_lag2"
 [476] "Master_mconsumototal_rank_lag2"
 [477] "Master_mpagominimo_rank_lag2"
 [478] "Visa_mfinanciacion_limite_rank_lag2"
 [479] "Visa_msaldototal_rank_lag2"
 [480] "Visa_msaldopesos_rank_lag2"
 [481] "Visa_msaldodolares_rank_lag2"
 [482] "Visa_mconsumospesos_rank_lag2"
 [483] "Visa_mconsumosdolares_rank_lag2"
 [484] "Visa_mlimitecompra_rank_lag2"
 [485] "Visa_madelantopesos_rank_lag2"
 [486] "Visa_madelantodolares_rank_lag2"
 [487] "Visa_mpagado_rank_lag2"
 [488] "Visa_mpagospesos_rank_lag2"
 [489] "Visa_mpagosdolares_rank_lag2"
 [490] "Visa_mconsumototal_rank_lag2"
 [491] "Visa_mpagominimo_rank_lag2"
 [492] "kmes_lag2"
 [493] "ctrx_quarter_normalizado_lag2"
 [494] "foto_mes_formato_fecha_lag2"
 [495] "vm_status01_lag2"
 [496] "vm_status02_lag2"
 [497] "vm_status03_lag2"
 [498] "vm_status04_lag2"
 [499] "vm_status05_lag2"
 [500] "vm_status06_lag2"
 [501] "mv_status07_lag2"
 [502] "vm_Fvencimiento_lag2"
 [503] "vm_Finiciomora_lag2"
 [504] "vm_fultimo_cierre_lag2"
 [505] "vm_fechaalta_lag2"
 [506] "vm_cconsumos_lag2"
 [507] "vm_cadelantosefectivo_lag2"
 [508] "active_quarter_delta1"
 [509] "active_quarter_delta2"
 [510] "cliente_vip_delta1"
 [511] "cliente_vip_delta2"
 [512] "internet_delta1"
 [513] "internet_delta2"
 [514] "cliente_edad_delta1"
 [515] "cliente_edad_delta2"
 [516] "cliente_antiguedad_delta1"
 [517] "cliente_antiguedad_delta2"
 [518] "cproductos_delta1"
 [519] "cproductos_delta2"
 [520] "tcuentas_delta1"
 [521] "tcuentas_delta2"
 [522] "ccuenta_corriente_delta1"
 [523] "ccuenta_corriente_delta2"
 [524] "ccaja_ahorro_delta1"
 [525] "ccaja_ahorro_delta2"
 [526] "cdescubierto_preacordado_delta1"
 [527] "cdescubierto_preacordado_delta2"
 [528] "ctarjeta_debito_delta1"
 [529] "ctarjeta_debito_delta2"
 [530] "ctarjeta_debito_transacciones_delta1"
 [531] "ctarjeta_debito_transacciones_delta2"
 [532] "ctarjeta_visa_delta1"
 [533] "ctarjeta_visa_delta2"
 [534] "ctarjeta_visa_transacciones_delta1"
 [535] "ctarjeta_visa_transacciones_delta2"
 [536] "ctarjeta_master_delta1"
 [537] "ctarjeta_master_delta2"
 [538] "ctarjeta_master_transacciones_delta1"
 [539] "ctarjeta_master_transacciones_delta2"
 [540] "cprestamos_personales_delta1"
 [541] "cprestamos_personales_delta2"
 [542] "cprestamos_prendarios_delta1"
 [543] "cprestamos_prendarios_delta2"
 [544] "cprestamos_hipotecarios_delta1"
 [545] "cprestamos_hipotecarios_delta2"
 [546] "cplazo_fijo_delta1"
 [547] "cplazo_fijo_delta2"
 [548] "cinversion1_delta1"
 [549] "cinversion1_delta2"
 [550] "cinversion2_delta1"
 [551] "cinversion2_delta2"
 [552] "cseguro_vida_delta1"
 [553] "cseguro_vida_delta2"
 [554] "cseguro_auto_delta1"
 [555] "cseguro_auto_delta2"
 [556] "cseguro_vivienda_delta1"
 [557] "cseguro_vivienda_delta2"
 [558] "cseguro_accidentes_personales_delta1"
 [559] "cseguro_accidentes_personales_delta2"
 [560] "ccaja_seguridad_delta1"
 [561] "ccaja_seguridad_delta2"
 [562] "cpayroll_trx_delta1"
 [563] "cpayroll_trx_delta2"
 [564] "cpayroll2_trx_delta1"
 [565] "cpayroll2_trx_delta2"
 [566] "ccuenta_debitos_automaticos_delta1"
 [567] "ccuenta_debitos_automaticos_delta2"
 [568] "ctarjeta_visa_debitos_automaticos_delta1"
 [569] "ctarjeta_visa_debitos_automaticos_delta2"
 [570] "ctarjeta_master_debitos_automaticos_delta1"
 [571] "ctarjeta_master_debitos_automaticos_delta2"
 [572] "cpagodeservicios_delta1"
 [573] "cpagodeservicios_delta2"
 [574] "cpagomiscuentas_delta1"
 [575] "cpagomiscuentas_delta2"
 [576] "ccajeros_propios_descuentos_delta1"
 [577] "ccajeros_propios_descuentos_delta2"
 [578] "ctarjeta_visa_descuentos_delta1"
 [579] "ctarjeta_visa_descuentos_delta2"
 [580] "ctarjeta_master_descuentos_delta1"
 [581] "ctarjeta_master_descuentos_delta2"
 [582] "ccomisiones_mantenimiento_delta1"
 [583] "ccomisiones_mantenimiento_delta2"
 [584] "ccomisiones_otras_delta1"
 [585] "ccomisiones_otras_delta2"
 [586] "cforex_delta1"
 [587] "cforex_delta2"
 [588] "cforex_buy_delta1"
 [589] "cforex_buy_delta2"
 [590] "cforex_sell_delta1"
 [591] "cforex_sell_delta2"
 [592] "ctransferencias_recibidas_delta1"
 [593] "ctransferencias_recibidas_delta2"
 [594] "ctransferencias_emitidas_delta1"

#### 9.7.1.5  FE_rf Feature Engineering de nuevas variables a partir de hojas de Random Forest

In [39]:
if( !require("lightgbm")) install.packages("lightgbm")
require("lightgbm")

Loading required package: lightgbm

In [40]:
AgregaVarRandomForest <- function() {

  cat( "inicio AgregaVarRandomForest()\n")
  gc(verbose= FALSE)
  dataset[, clase01 := 0L ]
  dataset[ clase_ternaria %in% PARAM$FE_rf$train$clase01_valor1,
      clase01 := 1L ]

  campos_buenos <- setdiff(
    colnames(dataset),
    c( "clase_ternaria", "clase01")
  )

  dataset[, entrenamiento :=
    as.integer( foto_mes %in% PARAM$FE_rf$train$training )]

  dtrain <- lgb.Dataset(
    data = data.matrix(dataset[entrenamiento == TRUE, campos_buenos, with = FALSE]),
    label = dataset[entrenamiento == TRUE, clase01],
    free_raw_data = FALSE
  )

  modelo <- lgb.train(
     data = dtrain,
     param = PARAM$FE_rf$lgb_param,
     verbose = -100
  )

  cat( "Fin construccion RandomForest\n" )
  # grabo el modelo, achivo .model
  lgb.save(modelo, file="modelo.model" )

  qarbolitos <- copy(PARAM$FE_rf$lgb_param$num_iterations)

  periodos <- dataset[ , unique( foto_mes ) ]

  for( periodo in  periodos )
  {
    cat( "periodo = ", periodo, "\n" )
    datamatrix <- data.matrix(dataset[ foto_mes== periodo, campos_buenos, with = FALSE])

    cat( "Inicio prediccion\n" )
    prediccion <- predict(
        modelo,
        datamatrix,
        type = "leaf"
    )
    cat( "Fin prediccion\n" )

    for( arbolito in 1:qarbolitos )
    {
       cat( arbolito, " " )
       hojas_arbol <- unique(prediccion[ , arbolito])

       for (pos in 1:length(hojas_arbol)) {
         # el numero de nodo de la hoja, estan salteados
         nodo_id <- hojas_arbol[pos]
         dataset[ foto_mes== periodo, paste0(
            "rf_", sprintf("%03d", arbolito),
             "_", sprintf("%03d", nodo_id)
          ) :=  as.integer( nodo_id == prediccion[ , arbolito]) ]

       }

       rm( hojas_arbol )
    }
    cat( "\n" )

    rm( prediccion )
    rm( datamatrix )
    gc(verbose= FALSE)
  }

  gc(verbose= FALSE)

  # borro clase01 , no debe ensuciar el dataset
  dataset[ , clase01 := NULL ]

}

In [41]:
# Parametros de Feature Engineering  a partir de hojas de Random Forest

# Estos CUATRO parametros son los que se deben modificar
PARAM$FE_rf$arbolitos= 20
PARAM$FE_rf$hojas_por_arbol= 16
PARAM$FE_rf$datos_por_hoja= 100
PARAM$FE_rf$mtry_ratio= 0.2

# Estos son quasi fijos
PARAM$FE_rf$train$clase01_valor1 <- c( "BAJA+2", "BAJA+1")
PARAM$FE_rf$train$training <- c( 202101, 202102, 202103)

# Estos TAMBIEN son quasi fijos
PARAM$FE_rf$lgb_param <-list(
    # parametros que se pueden cambiar
    num_iterations = PARAM$FE_rf$arbolitos,
    num_leaves  = PARAM$FE_rf$hojas_por_arbol,
    min_data_in_leaf = PARAM$FE_rf$datos_por_hoja,
    feature_fraction_bynode  = PARAM$FE_rf$mtry_ratio,

    # para que LightGBM emule Random Forest
    boosting = "rf",
    bagging_fraction = ( 1.0 - 1.0/exp(1.0) ),
    bagging_freq = 1.0,
    feature_fraction = 1.0,

    # genericos de LightGBM
    max_bin = 31L,
    objective = "binary",
    first_metric_only = TRUE,
    boost_from_average = TRUE,
    feature_pre_filter = FALSE,
    force_row_wise = TRUE,
    verbosity = -100,
    max_depth = -1L,
    min_gain_to_split = 0.0,
    min_sum_hessian_in_leaf = 0.001,
    lambda_l1 = 0.0,
    lambda_l2 = 0.0,

    pos_bagging_fraction = 1.0,
    neg_bagging_fraction = 1.0,
    is_unbalance = FALSE,
    scale_pos_weight = 1.0,

    drop_rate = 0.1,
    max_drop = 50,
    skip_drop = 0.5,

    extra_trees = FALSE
  )

In [42]:
# Feature Engineering agregando variables de Random Forest
AgregaVarRandomForest()

inicio AgregaVarRandomForest()
Fin construccion RandomForest
periodo =  201901
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201902
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201903
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201904
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201905
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201906
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201907
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201908
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201909
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201910
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201911
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201912
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202001
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202002
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202003
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202004
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202005
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202006
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202007
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202008
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202009
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202010
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202011
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202012
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202101
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202102
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202103
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202104
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202105
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202106
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202107
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202108
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202109
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20

In [43]:
ncol(dataset)
colnames(dataset)

[1] 1332

   [1] "numero_de_cliente"
   [2] "foto_mes"
   [3] "active_quarter"
   [4] "cliente_vip"
   [5] "internet"
   [6] "cliente_edad"
   [7] "cliente_antiguedad"
   [8] "cproductos"
   [9] "tcuentas"
  [10] "ccuenta_corriente"
  [11] "ccaja_ahorro"
  [12] "cdescubierto_preacordado"
  [13] "ctarjeta_debito"
  [14] "ctarjeta_debito_transacciones"
  [15] "ctarjeta_visa"
  [16] "ctarjeta_visa_transacciones"
  [17] "ctarjeta_master"
  [18] "ctarjeta_master_transacciones"
  [19] "cprestamos_personales"
  [20] "cprestamos_prendarios"
  [21] "cprestamos_hipotecarios"
  [22] "cplazo_fijo"
  [23] "cinversion1"
  [24] "cinversion2"
  [25] "cseguro_vida"
  [26] "cseguro_auto"
  [27] "cseguro_vivienda"
  [28] "cseguro_accidentes_personales"
  [29] "ccaja_seguridad"
  [30] "cpayroll_trx"
  [31] "cpayroll2_trx"
  [32] "ccuenta_debitos_automaticos"
  [33] "ctarjeta_visa_debitos_automaticos"
  [34] "ctarjeta_master_debitos_automaticos"
  [35] "cpagodeservicios"
  [36] "cpagomiscuentas"
  [37] "ccajeros_propios_descuentos"
  [38] "ctarjeta_visa_descuentos"
  [39] "ctarjeta_master_descuentos"
  [40] "ccomisiones_mantenimiento"
  [41] "ccomisiones_otras"
  [42] "cforex"
  [43] "cforex_buy"
  [44] "cforex_sell"
  [45] "ctransferencias_recibidas"
  [46] "ctransferencias_emitidas"
  [47] "cextraccion_autoservicio"
  [48] "ccheques_depositados"
  [49] "ccheques_emitidos"
  [50] "ccheques_depositados_rechazados"
  [51] "ccheques_emitidos_rechazados"
  [52] "tcallcenter"
  [53] "ccallcenter_transacciones"
  [54] "thomebanking"
  [55] "chomebanking_transacciones"
  [56] "ccajas_transacciones"
  [57] "ccajas_consultas"
  [58] "ccajas_depositos"
  [59] "ccajas_extracciones"
  [60] "ccajas_otras"
  [61] "catm_trx"
  [62] "catm_trx_other"
  [63] "ctrx_quarter"
  [64] "tmobile_app"
  [65] "cmobile_app_trx"
  [66] "Master_delinquency"
  [67] "Master_status"
  [68] "Master_Fvencimiento"
  [69] "Master_Finiciomora"
  [70] "Master_fultimo_cierre"
  [71] "Master_fechaalta"
  [72] "Master_cconsumos"
  [73] "Master_cadelantosefectivo"
  [74] "Visa_delinquency"
  [75] "Visa_status"
  [76] "Visa_Fvencimiento"
  [77] "Visa_Finiciomora"
  [78] "Visa_fultimo_cierre"
  [79] "Visa_fechaalta"
  [80] "Visa_cconsumos"
  [81] "Visa_cadelantosefectivo"
  [82] "clase_ternaria"
  [83] "mrentabilidad_rank"
  [84] "mrentabilidad_annual_rank"
  [85] "mcomisiones_rank"
  [86] "mactivos_margen_rank"
  [87] "mpasivos_margen_rank"
  [88] "mcuenta_corriente_adicional_rank"
  [89] "mcuenta_corriente_rank"
  [90] "mcaja_ahorro_rank"
  [91] "mcaja_ahorro_adicional_rank"
  [92] "mcaja_ahorro_dolares_rank"
  [93] "mcuentas_saldo_rank"
  [94] "mautoservicio_rank"
  [95] "mtarjeta_visa_consumo_rank"
  [96] "mtarjeta_master_consumo_rank"
  [97] "mprestamos_personales_rank"
  [98] "mprestamos_prendarios_rank"
  [99] "mprestamos_hipotecarios_rank"
 [100] "mplazo_fijo_dolares_rank"
 [101] "mplazo_fijo_pesos_rank"
 [102] "minversion1_pesos_rank"
 [103] "minversion1_dolares_rank"
 [104] "minversion2_rank"
 [105] "mpayroll_rank"
 [106] "mpayroll2_rank"
 [107] "mcuenta_debitos_automaticos_rank"
 [108] "mttarjeta_visa_debitos_automaticos_rank"
 [109] "mttarjeta_master_debitos_automaticos_rank"
 [110] "mpagodeservicios_rank"
 [111] "mpagomiscuentas_rank"
 [112] "mcajeros_propios_descuentos_rank"
 [113] "mtarjeta_visa_descuentos_rank"
 [114] "mtarjeta_master_descuentos_rank"
 [115] "mcomisiones_mantenimiento_rank"
 [116] "mcomisiones_otras_rank"
 [117] "mforex_buy_rank"
 [118] "mforex_sell_rank"
 [119] "mtransferencias_recibidas_rank"
 [120] "mtransferencias_emitidas_rank"
 [121] "mextraccion_autoservicio_rank"
 [122] "mcheques_depositados_rank"
 [123] "mcheques_emitidos_rank"
 [124] "mcheques_depositados_rechazados_rank"
 [125] "mcheques_emitidos_rechazados_rank"
 [126] "matm_rank"
 [127] "matm_other_rank"
 [128] "Master_mfinanciacion_limite_rank"
 [129] "Master_msaldototal_rank"
 [130] "Master_msaldopesos_rank"
 [131] "Master_msaldodolares_rank"
 [132] "Master_mconsumospesos_rank"
 [133] "Master_mconsumosdolares_rank"
 [134] "Master_mlimitecompra_rank"
 [135] "Master_madelantopesos_rank"
 [136] "Master_madelantodolares_rank"
 [137] "Master_mpagado_rank"
 [138] "Master_mpagospesos_rank"
 [139] "Master_mpagosdolares_rank"
 [140] "Master_mconsumototal_rank"
 [141] "Master_mpagominimo_rank"
 [142] "Visa_mfinanciacion_limite_rank"
 [143] "Visa_msaldototal_rank"
 [144] "Visa_msaldopesos_rank"
 [145] "Visa_msaldodolares_rank"
 [146] "Visa_mconsumospesos_rank"
 [147] "Visa_mconsumosdolares_rank"
 [148] "Visa_mlimitecompra_rank"
 [149] "Visa_madelantopesos_rank"
 [150] "Visa_madelantodolares_rank"
 [151] "Visa_mpagado_rank"
 [152] "Visa_mpagospesos_rank"
 [153] "Visa_mpagosdolares_rank"
 [154] "Visa_mconsumototal_rank"
 [155] "Visa_mpagominimo_rank"
 [156] "kmes"
 [157] "ctrx_quarter_normalizado"
 [158] "foto_mes_formato_fecha"
 [159] "vm_status01"
 [160] "vm_status02"
 [161] "vm_status03"
 [162] "vm_status04"
 [163] "vm_status05"
 [164] "vm_status06"
 [165] "mv_status07"
 [166] "vm_Fvencimiento"
 [167] "vm_Finiciomora"
 [168] "vm_fultimo_cierre"
 [169] "vm_fechaalta"
 [170] "vm_cconsumos"
 [171] "vm_cadelantosefectivo"
 [172] "active_quarter_lag1"
 [173] "cliente_vip_lag1"
 [174] "internet_lag1"
 [175] "cliente_edad_lag1"
 [176] "cliente_antiguedad_lag1"
 [177] "cproductos_lag1"
 [178] "tcuentas_lag1"
 [179] "ccuenta_corriente_lag1"
 [180] "ccaja_ahorro_lag1"
 [181] "cdescubierto_preacordado_lag1"
 [182] "ctarjeta_debito_lag1"
 [183] "ctarjeta_debito_transacciones_lag1"
 [184] "ctarjeta_visa_lag1"
 [185] "ctarjeta_visa_transacciones_lag1"
 [186] "ctarjeta_master_lag1"
 [187] "ctarjeta_master_transacciones_lag1"
 [188] "cprestamos_personales_lag1"
 [189] "cprestamos_prendarios_lag1"
 [190] "cprestamos_hipotecarios_lag1"
 [191] "cplazo_fijo_lag1"
 [192] "cinversion1_lag1"
 [193] "cinversion2_lag1"
 [194] "cseguro_vida_lag1"
 [195] "cseguro_auto_lag1"
 [196] "cseguro_vivienda_lag1"
 [197] "cseguro_accidentes_personales_lag1"
 [198] "ccaja_seguridad_lag1"
 [199] "cpayroll_trx_lag1"
 [200] "cpayroll2_trx_lag1"
 [201] "ccuenta_debitos_automaticos_lag1"
 [202] "ctarjeta_visa_debitos_automaticos_lag1"
 [203] "ctarjeta_master_debitos_automaticos_lag1"
 [204] "cpagodeservicios_lag1"
 [205] "cpagomiscuentas_lag1"
 [206] "ccajeros_propios_descuentos_lag1"
 [207] "ctarjeta_visa_descuentos_lag1"
 [208] "ctarjeta_master_descuentos_lag1"
 [209] "ccomisiones_mantenimiento_lag1"
 [210] "ccomisiones_otras_lag1"
 [211] "cforex_lag1"
 [212] "cforex_buy_lag1"
 [213] "cforex_sell_lag1"
 [214] "ctransferencias_recibidas_lag1"
 [215] "ctransferencias_emitidas_lag1"
 [216] "cextraccion_autoservicio_lag1"
 [217] "ccheques_depositados_lag1"
 [218] "ccheques_emitidos_lag1"
 [219] "ccheques_depositados_rechazados_lag1"
 [220] "ccheques_emitidos_rechazados_lag1"
 [221] "tcallcenter_lag1"
 [222] "ccallcenter_transacciones_lag1"
 [223] "thomebanking_lag1"
 [224] "chomebanking_transacciones_lag1"
 [225] "ccajas_transacciones_lag1"
 [226] "ccajas_consultas_lag1"
 [227] "ccajas_depositos_lag1"
 [228] "ccajas_extracciones_lag1"
 [229] "ccajas_otras_lag1"
 [230] "catm_trx_lag1"
 [231] "catm_trx_other_lag1"
 [232] "ctrx_quarter_lag1"
 [233] "tmobile_app_lag1"
 [234] "cmobile_app_trx_lag1"
 [235] "Master_delinquency_lag1"
 [236] "Master_status_lag1"
 [237] "Master_Fvencimiento_lag1"
 [238] "Master_Finiciomora_lag1"
 [239] "Master_fultimo_cierre_lag1"
 [240] "Master_fechaalta_lag1"
 [241] "Master_cconsumos_lag1"
 [242] "Master_cadelantosefectivo_lag1"
 [243] "Visa_delinquency_lag1"
 [244] "Visa_status_lag1"
 [245] "Visa_Fvencimiento_lag1"
 [246] "Visa_Finiciomora_lag1"
 [247] "Visa_fultimo_cierre_lag1"
 [248] "Visa_fechaalta_lag1"
 [249] "Visa_cconsumos_lag1"
 [250] "Visa_cadelantosefectivo_lag1"
 [251] "mrentabilidad_rank_lag1"
 [252] "mrentabilidad_annual_rank_lag1"
 [253] "mcomisiones_rank_lag1"
 [254] "mactivos_margen_rank_lag1"
 [255] "mpasivos_margen_rank_lag1"
 [256] "mcuenta_corriente_adicional_rank_lag1"
 [257] "mcuenta_corriente_rank_lag1"
 [258] "mcaja_ahorro_rank_lag1"
 [259] "mcaja_ahorro_adicional_rank_lag1"
 [260] "mcaja_ahorro_dolares_rank_lag1"
 [261] "mcuentas_saldo_rank_lag1"
 [262] "mautoservicio_rank_lag1"
 [263] "mtarjeta_visa_consumo_rank_lag1"
 [264] "mtarjeta_master_consumo_rank_lag1"
 [265] "mprestamos_personales_rank_lag1"
 [266] "mprestamos_prendarios_rank_lag1"
 [267] "mprestamos_hipotecarios_rank_lag1"
 [268] "mplazo_fijo_dolares_rank_lag1"
 [269] "mplazo_fijo_pesos_rank_lag1"
 [270] "minversion1_pesos_rank_lag1"
 [271] "minversion1_dolares_rank_lag1"
 [272] "minversion2_rank_lag1"
 [273] "mpayroll_rank_lag1"
 [274] "mpayroll2_rank_lag1"
 [275] "mcuenta_debitos_automaticos_rank_lag1"
 [276] "mttarjeta_visa_debitos_automaticos_rank_lag1"
 [277] "mttarjeta_master_debitos_automaticos_rank_lag1"
 [278] "mpagodeservicios_rank_lag1"
 [279] "mpagomiscuentas_rank_lag1"
 [280] "mcajeros_propios_descuentos_rank_lag1"
 [281] "mtarjeta_visa_descuentos_rank_lag1"
 [282] "mtarjeta_master_descuentos_rank_lag1"
 [283] "mcomisiones_mantenimiento_rank_lag1"
 [284] "mcomisiones_otras_rank_lag1"
 [285] "mforex_buy_rank_lag1"
 [286] "mforex_sell_rank_lag1"
 [287] "mtransferencias_recibidas_rank_lag1"
 [288] "mtransferencias_emitidas_rank_lag1"
 [289] "mextraccion_autoservicio_rank_lag1"
 [290] "mcheques_depositados_rank_lag1"
 [291] "mcheques_emitidos_rank_lag1"
 [292] "mcheques_depositados_rechazados_rank_lag1"
 [293] "mcheques_emitidos_rechazados_rank_lag1"
 [294] "matm_rank_lag1"
 [295] "matm_other_rank_lag1"
 [296] "Master_mfinanciacion_limite_rank_lag1"
 [297] "Master_msaldototal_rank_lag1"
 [298] "Master_msaldopesos_rank_lag1"
 [299] "Master_msaldodolares_rank_lag1"
 [300] "Master_mconsumospesos_rank_lag1"
 [301] "Master_mconsumosdolares_rank_lag1"
 [302] "Master_mlimitecompra_rank_lag1"
 [303] "Master_madelantopesos_rank_lag1"
 [304] "Master_madelantodolares_rank_lag1"
 [305] "Master_mpagado_rank_lag1"
 [306] "Master_mpagospesos_rank_lag1"
 [307] "Master_mpagosdolares_rank_lag1"
 [308] "Master_mconsumototal_rank_lag1"
 [309] "Master_mpagominimo_rank_lag1"
 [310] "Visa_mfinanciacion_limite_rank_lag1"
 [311] "Visa_msaldototal_rank_lag1"
 [312] "Visa_msaldopesos_rank_lag1"
 [313] "Visa_msaldodolares_rank_lag1"
 [314] "Visa_mconsumospesos_rank_lag1"
 [315] "Visa_mconsumosdolares_rank_lag1"
 [316] "Visa_mlimitecompra_rank_lag1"
 [317] "Visa_madelantopesos_rank_lag1"
 [318] "Visa_madelantodolares_rank_lag1"
 [319] "Visa_mpagado_rank_lag1"
 [320] "Visa_mpagospesos_rank_lag1"
 [321] "Visa_mpagosdolares_rank_lag1"
 [322] "Visa_mconsumototal_rank_lag1"
 [323] "Visa_mpagominimo_rank_lag1"
 [324] "kmes_lag1"
 [325] "ctrx_quarter_normalizado_lag1"
 [326] "foto_mes_formato_fecha_lag1"
 [327] "vm_status01_lag1"
 [328] "vm_status02_lag1"
 [329] "vm_status03_lag1"
 [330] "vm_status04_lag1"
 [331] "vm_status05_lag1"
 [332] "vm_status06_lag1"
 [333] "mv_status07_lag1"
 [334] "vm_Fvencimiento_lag1"
 [335] "vm_Finiciomora_lag1"
 [336] "vm_fultimo_cierre_lag1"
 [337] "vm_fechaalta_lag1"
 [338] "vm_cconsumos_lag1"
 [339] "vm_cadelantosefectivo_lag1"
 [340] "active_quarter_lag2"
 [341] "cliente_vip_lag2"
 [342] "internet_lag2"
 [343] "cliente_edad_lag2"
 [344] "cliente_antiguedad_lag2"
 [345] "cproductos_lag2"
 [346] "tcuentas_lag2"
 [347] "ccuenta_corriente_lag2"
 [348] "ccaja_ahorro_lag2"
 [349] "cdescubierto_preacordado_lag2"
 [350] "ctarjeta_debito_lag2"
 [351] "ctarjeta_debito_transacciones_lag2"
 [352] "ctarjeta_visa_lag2"
 [353] "ctarjeta_visa_transacciones_lag2"
 [354] "ctarjeta_master_lag2"
 [355] "ctarjeta_master_transacciones_lag2"
 [356] "cprestamos_personales_lag2"
 [357] "cprestamos_prendarios_lag2"
 [358] "cprestamos_hipotecarios_lag2"
 [359] "cplazo_fijo_lag2"
 [360] "cinversion1_lag2"
 [361] "cinversion2_lag2"
 [362] "cseguro_vida_lag2"
 [363] "cseguro_auto_lag2"
 [364] "cseguro_vivienda_lag2"
 [365] "cseguro_accidentes_personales_lag2"
 [366] "ccaja_seguridad_lag2"
 [367] "cpayroll_trx_lag2"
 [368] "cpayroll2_trx_lag2"
 [369] "ccuenta_debitos_automaticos_lag2"
 [370] "ctarjeta_visa_debitos_automaticos_lag2"
 [371] "ctarjeta_master_debitos_automaticos_lag2"
 [372] "cpagodeservicios_lag2"
 [373] "cpagomiscuentas_lag2"
 [374] "ccajeros_propios_descuentos_lag2"
 [375] "ctarjeta_visa_descuentos_lag2"
 [376] "ctarjeta_master_descuentos_lag2"
 [377] "ccomisiones_mantenimiento_lag2"
 [378] "ccomisiones_otras_lag2"
 [379] "cforex_lag2"
 [380] "cforex_buy_lag2"
 [381] "cforex_sell_lag2"
 [382] "ctransferencias_recibidas_lag2"
 [383] "ctransferencias_emitidas_lag2"
 [384] "cextraccion_autoservicio_lag2"
 [385] "ccheques_depositados_lag2"
 [386] "ccheques_emitidos_lag2"
 [387] "ccheques_depositados_rechazados_lag2"
 [388] "ccheques_emitidos_rechazados_lag2"
 [389] "tcallcenter_lag2"
 [390] "ccallcenter_transacciones_lag2"
 [391] "thomebanking_lag2"
 [392] "chomebanking_transacciones_lag2"
 [393] "ccajas_transacciones_lag2"
 [394] "ccajas_consultas_lag2"
 [395] "ccajas_depositos_lag2"
 [396] "ccajas_extracciones_lag2"
 [397] "ccajas_otras_lag2"
 [398] "catm_trx_lag2"
 [399] "catm_trx_other_lag2"
 [400] "ctrx_quarter_lag2"
 [401] "tmobile_app_lag2"
 [402] "cmobile_app_trx_lag2"
 [403] "Master_delinquency_lag2"
 [404] "Master_status_lag2"
 [405] "Master_Fvencimiento_lag2"
 [406] "Master_Finiciomora_lag2"
 [407] "Master_fultimo_cierre_lag2"
 [408] "Master_fechaalta_lag2"
 [409] "Master_cconsumos_lag2"
 [410] "Master_cadelantosefectivo_lag2"
 [411] "Visa_delinquency_lag2"
 [412] "Visa_status_lag2"
 [413] "Visa_Fvencimiento_lag2"
 [414] "Visa_Finiciomora_lag2"
 [415] "Visa_fultimo_cierre_lag2"
 [416] "Visa_fechaalta_lag2"
 [417] "Visa_cconsumos_lag2"
 [418] "Visa_cadelantosefectivo_lag2"
 [419] "mrentabilidad_rank_lag2"
 [420] "mrentabilidad_annual_rank_lag2"
 [421] "mcomisiones_rank_lag2"
 [422] "mactivos_margen_rank_lag2"
 [423] "mpasivos_margen_rank_lag2"
 [424] "mcuenta_corriente_adicional_rank_lag2"
 [425] "mcuenta_corriente_rank_lag2"
 [426] "mcaja_ahorro_rank_lag2"
 [427] "mcaja_ahorro_adicional_rank_lag2"
 [428] "mcaja_ahorro_dolares_rank_lag2"
 [429] "mcuentas_saldo_rank_lag2"
 [430] "mautoservicio_rank_lag2"
 [431] "mtarjeta_visa_consumo_rank_lag2"
 [432] "mtarjeta_master_consumo_rank_lag2"
 [433] "mprestamos_personales_rank_lag2"
 [434] "mprestamos_prendarios_rank_lag2"
 [435] "mprestamos_hipotecarios_rank_lag2"
 [436] "mplazo_fijo_dolares_rank_lag2"
 [437] "mplazo_fijo_pesos_rank_lag2"
 [438] "minversion1_pesos_rank_lag2"
 [439] "minversion1_dolares_rank_lag2"
 [440] "minversion2_rank_lag2"
 [441] "mpayroll_rank_lag2"
 [442] "mpayroll2_rank_lag2"
 [443] "mcuenta_debitos_automaticos_rank_lag2"
 [444] "mttarjeta_visa_debitos_automaticos_rank_lag2"
 [445] "mttarjeta_master_debitos_automaticos_rank_lag2"
 [446] "mpagodeservicios_rank_lag2"
 [447] "mpagomiscuentas_rank_lag2"
 [448] "mcajeros_propios_descuentos_rank_lag2"
 [449] "mtarjeta_visa_descuentos_rank_lag2"
 [450] "mtarjeta_master_descuentos_rank_lag2"
 [451] "mcomisiones_mantenimiento_rank_lag2"
 [452] "mcomisiones_otras_rank_lag2"
 [453] "mforex_buy_rank_lag2"
 [454] "mforex_sell_rank_lag2"
 [455] "mtransferencias_recibidas_rank_lag2"
 [456] "mtransferencias_emitidas_rank_lag2"
 [457] "mextraccion_autoservicio_rank_lag2"
 [458] "mcheques_depositados_rank_lag2"
 [459] "mcheques_emitidos_rank_lag2"
 [460] "mcheques_depositados_rechazados_rank_lag2"
 [461] "mcheques_emitidos_rechazados_rank_lag2"
 [462] "matm_rank_lag2"
 [463] "matm_other_rank_lag2"
 [464] "Master_mfinanciacion_limite_rank_lag2"
 [465] "Master_msaldototal_rank_lag2"
 [466] "Master_msaldopesos_rank_lag2"
 [467] "Master_msaldodolares_rank_lag2"
 [468] "Master_mconsumospesos_rank_lag2"
 [469] "Master_mconsumosdolares_rank_lag2"
 [470] "Master_mlimitecompra_rank_lag2"
 [471] "Master_madelantopesos_rank_lag2"
 [472] "Master_madelantodolares_rank_lag2"
 [473] "Master_mpagado_rank_lag2"
 [474] "Master_mpagospesos_rank_lag2"
 [475] "Master_mpagosdolares_rank_lag2"
 [476] "Master_mconsumototal_rank_lag2"
 [477] "Master_mpagominimo_rank_lag2"
 [478] "Visa_mfinanciacion_limite_rank_lag2"
 [479] "Visa_msaldototal_rank_lag2"
 [480] "Visa_msaldopesos_rank_lag2"
 [481] "Visa_msaldodolares_rank_lag2"
 [482] "Visa_mconsumospesos_rank_lag2"
 [483] "Visa_mconsumosdolares_rank_lag2"
 [484] "Visa_mlimitecompra_rank_lag2"
 [485] "Visa_madelantopesos_rank_lag2"
 [486] "Visa_madelantodolares_rank_lag2"
 [487] "Visa_mpagado_rank_lag2"
 [488] "Visa_mpagospesos_rank_lag2"
 [489] "Visa_mpagosdolares_rank_lag2"
 [490] "Visa_mconsumototal_rank_lag2"
 [491] "Visa_mpagominimo_rank_lag2"
 [492] "kmes_lag2"
 [493] "ctrx_quarter_normalizado_lag2"
 [494] "foto_mes_formato_fecha_lag2"
 [495] "vm_status01_lag2"
 [496] "vm_status02_lag2"
 [497] "vm_status03_lag2"
 [498] "vm_status04_lag2"
 [499] "vm_status05_lag2"
 [500] "vm_status06_lag2"
 [501] "mv_status07_lag2"
 [502] "vm_Fvencimiento_lag2"
 [503] "vm_Finiciomora_lag2"
 [504] "vm_fultimo_cierre_lag2"
 [505] "vm_fechaalta_lag2"
 [506] "vm_cconsumos_lag2"
 [507] "vm_cadelantosefectivo_lag2"
 [508] "active_quarter_delta1"
 [509] "active_quarter_delta2"
 [510] "cliente_vip_delta1"
 [511] "cliente_vip_delta2"
 [512] "internet_delta1"
 [513] "internet_delta2"
 [514] "cliente_edad_delta1"
 [515] "cliente_edad_delta2"
 [516] "cliente_antiguedad_delta1"
 [517] "cliente_antiguedad_delta2"
 [518] "cproductos_delta1"
 [519] "cproductos_delta2"
 [520] "tcuentas_delta1"
 [521] "tcuentas_delta2"
 [522] "ccuenta_corriente_delta1"
 [523] "ccuenta_corriente_delta2"
 [524] "ccaja_ahorro_delta1"
 [525] "ccaja_ahorro_delta2"
 [526] "cdescubierto_preacordado_delta1"
 [527] "cdescubierto_preacordado_delta2"
 [528] "ctarjeta_debito_delta1"
 [529] "ctarjeta_debito_delta2"
 [530] "ctarjeta_debito_transacciones_delta1"
 [531] "ctarjeta_debito_transacciones_delta2"
 [532] "ctarjeta_visa_delta1"
 [533] "ctarjeta_visa_delta2"
 [534] "ctarjeta_visa_transacciones_delta1"
 [535] "ctarjeta_visa_transacciones_delta2"
 [536] "ctarjeta_master_delta1"
 [537] "ctarjeta_master_delta2"
 [538] "ctarjeta_master_transacciones_delta1"
 [539] "ctarjeta_master_transacciones_delta2"
 [540] "cprestamos_personales_delta1"
 [541] "cprestamos_personales_delta2"
 [542] "cprestamos_prendarios_delta1"
 [543] "cprestamos_prendarios_delta2"
 [544] "cprestamos_hipotecarios_delta1"
 [545] "cprestamos_hipotecarios_delta2"
 [546] "cplazo_fijo_delta1"
 [547] "cplazo_fijo_delta2"
 [548] "cinversion1_delta1"
 [549] "cinversion1_delta2"
 [550] "cinversion2_delta1"
 [551] "cinversion2_delta2"
 [552] "cseguro_vida_delta1"
 [553] "cseguro_vida_delta2"
 [554] "cseguro_auto_delta1"
 [555] "cseguro_auto_delta2"
 [556] "cseguro_vivienda_delta1"
 [557] "cseguro_vivienda_delta2"
 [558] "cseguro_accidentes_personales_delta1"
 [559] "cseguro_accidentes_personales_delta2"
 [560] "ccaja_seguridad_delta1"
 [561] "ccaja_seguridad_delta2"
 [562] "cpayroll_trx_delta1"
 [563] "cpayroll_trx_delta2"
 [564] "cpayroll2_trx_delta1"
 [565] "cpayroll2_trx_delta2"
 [566] "ccuenta_debitos_automaticos_delta1"
 [567] "ccuenta_debitos_automaticos_delta2"
 [568] "ctarjeta_visa_debitos_automaticos_delta1"
 [569] "ctarjeta_visa_debitos_automaticos_delta2"
 [570] "ctarjeta_master_debitos_automaticos_delta1"
 [571] "ctarjeta_master_debitos_automaticos_delta2"
 [572] "cpagodeservicios_delta1"
 [573] "cpagodeservicios_delta2"
 [574] "cpagomiscuentas_delta1"
 [575] "cpagomiscuentas_delta2"
 [576] "ccajeros_propios_descuentos_delta1"
 [577] "ccajeros_propios_descuentos_delta2"
 [578] "ctarjeta_visa_descuentos_delta1"
 [579] "ctarjeta_visa_descuentos_delta2"
 [580] "ctarjeta_master_descuentos_delta1"
 [581] "ctarjeta_master_descuentos_delta2"
 [582] "ccomisiones_mantenimiento_delta1"
 [583] "ccomisiones_mantenimiento_delta2"
 [584] "ccomisiones_otras_delta1"
 [585] "ccomisiones_otras_delta2"
 [586] "cforex_delta1"
 [587] "cforex_delta2"
 [588] "cforex_buy_delta1"
 [589] "cforex_buy_delta2"
 [590] "cforex_sell_delta1"
 [591] "cforex_sell_delta2"
 [592] "ctransferencias_recibidas_delta1"
 [593] "ctransferencias_recibidas_delta2"
 [594] "ctransferencias_emitidas_delta1"

#### 9.7.1.6  FEhist Reduccion dimensionalidad con canaritos

Esta etapa solo se mostrará a la *modalidad Anlista Sr*

El objetivo de esta etapa NO es mejorar el modelo predictivo

El objetivo es eliminar campos poco importantes para hacer espacio a nuevos campos, debido a las restricciones de memoria RAM.

In [44]:
VPOS_CORTE <- c()

fganancia_lgbm_meseta <- function(probs, datos) {
  vlabels <- get_field(datos, "label")
  vpesos <- get_field(datos, "weight")

  tbl <- as.data.table(list(
    "prob" = probs,
    "gan" = ifelse(vlabels == 1 & vpesos > 1, PARAM$CN$train$gan1, PARAM$CN$train$gan0)
  ))

  setorder(tbl, -prob)
  tbl[, posicion := .I]
  tbl[, gan_acum := cumsum(gan)]
  setorder(tbl, -gan_acum) # voy por la meseta

  gan <- mean(tbl[1:500, gan_acum]) # meseta de tamaño 500

  pos_meseta <- tbl[1:500, median(posicion)]
  VPOS_CORTE <<- c(VPOS_CORTE, pos_meseta)

  return(list(
    "name" = "ganancia",
    "value" = gan,
    "higher_better" = TRUE
  ))
}

In [45]:
# Elimina del dataset las variables que estan por debajo
#  de la capa geologica de canaritos
# se llama varias veces, luego de agregar muchas variables nuevas,
#  para ir reduciendo la cantidad de variables
# y así hacer lugar a nuevas variables importantes

GVEZ <- 1

campitos <- c( "numero_de_cliente", "foto_mes", "clase_ternaria" )

CanaritosAsesinos <- function(
  canaritos_ratio,
  canaritos_desvios,
  canaritos_semilla) {

  cat( "inicio CanaritosAsesinos()\n")
  gc(verbose= FALSE)
  dataset[, clase01 := 0L ]
  dataset[ clase_ternaria %in% PARAM$CN$train$clase01_valor1,
      clase01 := 1L ]

  set.seed(canaritos_semilla, kind = "L'Ecuyer-CMRG")
  for (i in 1:(ncol(dataset) * canaritos_ratio)) {
    dataset[, paste0("canarito", i) := runif(nrow(dataset))]
  }

  campos_buenos <- setdiff(
    colnames(dataset),
    c( campitos, "clase01")
  )

  azar <- runif(nrow(dataset))

  dataset[, entrenamiento :=
    as.integer( foto_mes %in% PARAM$CN$train$training &
      (clase01 == 1 | azar < PARAM$CN$train$undersampling))]

  dtrain <- lgb.Dataset(
    data = data.matrix(dataset[entrenamiento == TRUE, campos_buenos, with = FALSE]),
    label = dataset[entrenamiento == TRUE, clase01],
    weight = dataset[
      entrenamiento == TRUE,
      ifelse(clase_ternaria %in% PARAM$CN$train$positivos, 1.0000001, 1.0)
    ],
    free_raw_data = FALSE
  )

  dvalid <- lgb.Dataset(
    data = data.matrix(dataset[foto_mes %in% PARAM$CN$train$validation, campos_buenos, with = FALSE]),
    label = dataset[foto_mes %in% PARAM$CN$train$validation, clase01],
    weight = dataset[
      foto_mes %in% PARAM$CN$train$validation,
      ifelse( clase_ternaria %in% PARAM$CN$train$positivos, 1.0000001, 1.0)
    ],
    free_raw_data = FALSE
  )


  param <- list(
    objective = "binary",
    metric = "custom",
    first_metric_only = TRUE,
    boost_from_average = TRUE,
    feature_pre_filter = FALSE,
    verbosity = -100,
    seed = canaritos_semilla,
    max_depth = -1, # -1 significa no limitar,  por ahora lo dejo fijo
    min_gain_to_split = 0.0, # por ahora, lo dejo fijo
    lambda_l1 = 0.0, # por ahora, lo dejo fijo
    lambda_l2 = 0.0, # por ahora, lo dejo fijo
    max_bin = 31, # por ahora, lo dejo fijo
    num_iterations = 9999, # un numero grande, lo limita early_stopping_rounds
    force_row_wise = TRUE, # para que los alumnos no se atemoricen con  warning
    learning_rate = 0.065,
    feature_fraction = 1.0, # lo seteo en 1
    min_data_in_leaf = 260,
    num_leaves = 60,
    early_stopping_rounds = 200,
    num_threads = 1
  )

  set.seed(canaritos_semilla, kind = "L'Ecuyer-CMRG")
  modelo <- lgb.train(
    data = dtrain,
    valids = list(valid = dvalid),
    eval = fganancia_lgbm_meseta,
    param = param,
    verbose = -100
  )

  tb_importancia <- lgb.importance(model = modelo)
  tb_importancia[, pos := .I]

  fwrite(tb_importancia,
    file = paste0("impo_", GVEZ, ".txt"),
    sep = "\t"
  )

  GVEZ <<- GVEZ + 1

  umbral <- tb_importancia[
    Feature %like% "canarito",
    median(pos) + canaritos_desvios * sd(pos)
  ] # Atencion corto en la mediana mas desvios!!

  col_utiles <- tb_importancia[
    pos < umbral & !(Feature %like% "canarito"),
    Feature
  ]

  col_utiles <- unique(c(
    col_utiles,
    c(campitos, "mes")
  ))

  col_inutiles <- setdiff(colnames(dataset), col_utiles)

  dataset[, (col_inutiles) := NULL]

  cat( "fin CanaritosAsesinos()\n")

  return( tb_importancia )
}

In [46]:
# Estos DOS parametros son los que se deben modificar
PARAM$CN$ratio <- 0.2
PARAM$CN$desvios <- 2


# Parametros quasi fijos
# Parametros de un LightGBM que se genera para estimar la column importance
PARAM$CN$train$clase01_valor1 <- c( "BAJA+2", "BAJA+1")
PARAM$CN$train$positivos <- c( "BAJA+2")
PARAM$CN$train$training <- c( 202101, 202102, 202103)
PARAM$CN$train$validation <- c( 202105 )
PARAM$CN$train$undersampling <- 0.1
PARAM$CN$train$gan1 <- 0.975
PARAM$CN$train$gan0 <- -0.025

In [47]:
if (PARAM$FS$selector == "boruta") {
  # ==== BORUTA: seleccion de variables "a lo Canaritos" ====
  #  se ejecuta solo si  PARAM$FS$selector == "boruta"
  #  adaptado de v950-workflow-01-boruta-014
  
  if( !require("Boruta")) install.packages("Boruta", repos = "http://cran.us.r-project.org")
  require("Boruta")
  
  # ranger es un backend de Random Forest mucho mas rapido; si esta instalado se usa solo
  if( !require("ranger")) install.packages("ranger", repos = "http://cran.us.r-project.org")
  require("ranger")
  
  # Boruta usa la config de entrenamiento de CN; si no existe, la definimos
  if( is.null(PARAM$CN$train) ) {
    PARAM$CN$train <- list(
      clase01_valor1 = c("BAJA+2", "BAJA+1"),
      training       = c(202101, 202102, 202103)
    )
  }
  
  BorutaSelector <- function(boruta_semilla = PARAM$semilla_primigenia) {
  
    cat( "inicio BorutaSelector()\n")
    gc(verbose= FALSE)
  
    # 0) target binaria consistente con CN
    dataset[, clase01 := 0L ]
    dataset[ clase_ternaria %in% PARAM$CN$train$clase01_valor1, clase01 := 1L ]
    dataset[, clase01 := factor(clase01, levels = c(0,1))]
  
    # 1) training + undersampling (igual que Canaritos)
    set.seed(boruta_semilla, kind = "L'Ecuyer-CMRG")
    azar <- runif(nrow(dataset))
    dt_tr_bor <- copy(
      dataset[
        foto_mes %in% PARAM$CN$train$training &
        (clase01 == 1 | azar < PARAM$BR$undersampling)
      ]
    )
  
    # 2) predictores (sin keys ni clases)
    campitos  <- c("numero_de_cliente","foto_mes","clase_ternaria","clase01")
    pred_cols <- setdiff(names(dt_tr_bor), campitos)
  
    # 2.a) quitar columnas constantes o con >95% NA (ahorra RAM/tiempo)
    const <- pred_cols[vapply(pred_cols,
      function(v) data.table::uniqueN(dt_tr_bor[[v]], na.rm=TRUE) <= 1L, logical(1))]
    hi_na <- pred_cols[vapply(pred_cols,
      function(v) mean(is.na(dt_tr_bor[[v]])) > 0.95, logical(1))]
    pred_cols <- setdiff(pred_cols, union(const, hi_na))
  
    # 2.b) tipos: char -> factor
    for (v in pred_cols) if (is.character(dt_tr_bor[[v]])) dt_tr_bor[, (v) := factor(get(v))]
  
    # 2.c) imputacion simple SOLO para Boruta (respetando tipo original)
    for (v in pred_cols) {
      col <- dt_tr_bor[[v]]
  
      if (is.integer(col)) {
        m <- suppressWarnings(median(as.numeric(col), na.rm = TRUE))
        if (!is.finite(m)) m <- 0
        set(dt_tr_bor, which(is.na(col)), v, as.integer(round(m)))
  
      } else if (is.numeric(col)) {
        m <- suppressWarnings(median(col, na.rm = TRUE))
        if (!is.finite(m)) m <- 0
        set(dt_tr_bor, which(is.na(col)), v, m)
  
      } else if (is.factor(col)) {
        if (anyNA(col)) {
          dt_tr_bor[, (v) := fcase(is.na(get(v)), "Missing", default = as.character(get(v)))]
          dt_tr_bor[, (v) := factor(get(v))]
        }
      }
    }
  
    # 3) pesos de clase (OPCIONAL, default vanilla = sin pesos,
    #    igual que Canaritos que solo hace undersampling)
    if( PARAM$BR$classweights ) {
      n0 <- sum(dt_tr_bor$clase01 == 0)
      n1 <- sum(dt_tr_bor$clase01 == 1)
      class_w <- c("0" = 1, "1" = ifelse(n1 > 0, n0/n1, 1))
    } else {
      class_w <- NULL
    }
  
    # 4) BORUTA (detecta backend y pasa class weights solo si corresponde)
    use_ranger <- requireNamespace("ranger", quietly = TRUE)
  
    bor_args <- list(
      x           = as.data.frame(dt_tr_bor[, ..pred_cols]),
      y           = dt_tr_bor$clase01,
      doTrace     = 2,
      ntree       = PARAM$BR$ntree,
      maxRuns     = PARAM$BR$maxRuns,
      pValue      = PARAM$BR$pValue,
      mcAdj       = PARAM$BR$mcAdj,
      getImp      = getImpRfZ,
      holdHistory = PARAM$BR$holdHistory
      # max.depth   = 16
    )
    if( PARAM$BR$threads > 0L ) bor_args$num.threads <- PARAM$BR$threads
    if( !is.null(class_w) ) {
      if (use_ranger) bor_args$class.weights <- class_w else bor_args$classwt <- class_w
    }
  
    set.seed(boruta_semilla, kind = "L'Ecuyer-CMRG")
    bor_fit  <- do.call(Boruta, bor_args)
    # TentativeRoughFix exige holdHistory=TRUE;
    #  si se corrio sin historia, los tentative simplemente quedan afuera
    if( PARAM$BR$holdHistory ) {
      bor_fix <- TentativeRoughFix(bor_fit)
    } else {
      bor_fix <- bor_fit
    }
  
    # 5) resultados y persistencias
    bor_stats <- as.data.table(attStats(bor_fix), keep.rownames = "variable")
    sel_vars  <- getSelectedAttributes(bor_fix, withTentative = FALSE)
  
    fwrite(bor_stats,                    "boruta_stats.txt", sep = "\t")
    fwrite(data.table(variable=sel_vars),"boruta.txt",      sep = "\t")
  
    cat(sprintf("BORUTA: candidatos=%d  seleccionados=%d\n",
      length(pred_cols), length(sel_vars)))
  
    # 6) recorte del dataset GLOBAL, igual que hace CanaritosAsesinos
    keep_cols <- unique(c(campitos, sel_vars))
    keep_cols <- intersect(keep_cols, names(dataset))
    dataset[, (setdiff(names(dataset), keep_cols)) := NULL]
  
    cat( "fin BorutaSelector()\n")
  
    invisible( bor_stats )
  }
} else {
  cat("skip Boruta install/define - canarito only\n")
}

skip Boruta install/define - canarito only

In [48]:
# seleccion de variables, segun  PARAM$FS$selector  (canarito | boruta)
if( PARAM$FS$selector == "boruta" ) {
  cat("Seleccion de variables: BORUTA\n")
  tb_boruta <- BorutaSelector(
    boruta_semilla = PARAM$semilla_primigenia
  )
} else {
  cat("Seleccion de variables: CANARITOS ASESINOS\n")
  tb_importancia <- CanaritosAsesinos(
    canaritos_ratio = PARAM$CN$ratio,
    canaritos_desvios = PARAM$CN$desvios,
    canaritos_semilla = PARAM$semilla_primigenia
  )
}

Seleccion de variables: CANARITOS ASESINOS
inicio CanaritosAsesinos()
fin CanaritosAsesinos()

In [49]:
# grabo la importancia, ver el archivo directamente en la carpeta
if( PARAM$FS$selector == "canarito" ) {
  fwrite( tb_importancia,
    file="canaritos.txt",
    sep="\t"
  )
}

In [50]:
# verifico
ncol(dataset)
colnames(dataset)

[1] 444

  [1] "numero_de_cliente"
  [2] "foto_mes"
  [3] "internet"
  [4] "cliente_edad"
  [5] "cliente_antiguedad"
  [6] "cproductos"
  [7] "ccaja_ahorro"
  [8] "cdescubierto_preacordado"
  [9] "ctarjeta_debito_transacciones"
 [10] "ctarjeta_visa"
 [11] "ctarjeta_visa_transacciones"
 [12] "ctarjeta_master_transacciones"
 [13] "cprestamos_personales"
 [14] "ccaja_seguridad"
 [15] "cpayroll_trx"
 [16] "ccuenta_debitos_automaticos"
 [17] "ctarjeta_visa_debitos_automaticos"
 [18] "ccomisiones_otras"
 [19] "ctransferencias_recibidas"
 [20] "ctransferencias_emitidas"
 [21] "cextraccion_autoservicio"
 [22] "tcallcenter"
 [23] "thomebanking"
 [24] "chomebanking_transacciones"
 [25] "ccajas_consultas"
 [26] "ctrx_quarter"
 [27] "Master_status"
 [28] "Master_Fvencimiento"
 [29] "Master_fultimo_cierre"
 [30] "Master_fechaalta"
 [31] "Master_cconsumos"
 [32] "Visa_status"
 [33] "Visa_Fvencimiento"
 [34] "Visa_fechaalta"
 [35] "Visa_cconsumos"
 [36] "clase_ternaria"
 [37] "mrentabilidad_rank"
 [38] "mrentabilidad_annual_rank"
 [39] "mcomisiones_rank"
 [40] "mactivos_margen_rank"
 [41] "mpasivos_margen_rank"
 [42] "mcuenta_corriente_rank"
 [43] "mcaja_ahorro_rank"
 [44] "mcaja_ahorro_dolares_rank"
 [45] "mcuentas_saldo_rank"
 [46] "mautoservicio_rank"
 [47] "mtarjeta_visa_consumo_rank"
 [48] "mtarjeta_master_consumo_rank"
 [49] "mprestamos_personales_rank"
 [50] "mplazo_fijo_dolares_rank"
 [51] "minversion2_rank"
 [52] "mpayroll_rank"
 [53] "mcuenta_debitos_automaticos_rank"
 [54] "mttarjeta_visa_debitos_automaticos_rank"
 [55] "mpagomiscuentas_rank"
 [56] "mcomisiones_mantenimiento_rank"
 [57] "mcomisiones_otras_rank"
 [58] "mtransferencias_recibidas_rank"
 [59] "Master_mfinanciacion_limite_rank"
 [60] "Master_msaldototal_rank"
 [61] "Master_msaldopesos_rank"
 [62] "Master_msaldodolares_rank"
 [63] "Master_mconsumosdolares_rank"
 [64] "Master_mlimitecompra_rank"
 [65] "Master_mpagosdolares_rank"
 [66] "Master_mpagominimo_rank"
 [67] "Visa_mfinanciacion_limite_rank"
 [68] "Visa_msaldototal_rank"
 [69] "Visa_msaldopesos_rank"
 [70] "Visa_msaldodolares_rank"
 [71] "Visa_mconsumospesos_rank"
 [72] "Visa_mconsumosdolares_rank"
 [73] "Visa_mlimitecompra_rank"
 [74] "Visa_mpagospesos_rank"
 [75] "Visa_mpagominimo_rank"
 [76] "ctrx_quarter_normalizado"
 [77] "vm_status01"
 [78] "vm_status02"
 [79] "vm_status04"
 [80] "vm_status05"
 [81] "vm_Fvencimiento"
 [82] "vm_fultimo_cierre"
 [83] "vm_cconsumos"
 [84] "internet_lag1"
 [85] "cliente_edad_lag1"
 [86] "cliente_antiguedad_lag1"
 [87] "cproductos_lag1"
 [88] "ccaja_ahorro_lag1"
 [89] "ctarjeta_debito_transacciones_lag1"
 [90] "ctarjeta_visa_transacciones_lag1"
 [91] "ccaja_seguridad_lag1"
 [92] "cpayroll_trx_lag1"
 [93] "ccuenta_debitos_automaticos_lag1"
 [94] "ctarjeta_visa_debitos_automaticos_lag1"
 [95] "ccomisiones_otras_lag1"
 [96] "ctransferencias_emitidas_lag1"
 [97] "ccallcenter_transacciones_lag1"
 [98] "chomebanking_transacciones_lag1"
 [99] "ctrx_quarter_lag1"
[100] "cmobile_app_trx_lag1"
[101] "Master_Fvencimiento_lag1"
[102] "Master_fultimo_cierre_lag1"
[103] "Master_fechaalta_lag1"
[104] "Master_cconsumos_lag1"
[105] "Visa_Fvencimiento_lag1"
[106] "Visa_fultimo_cierre_lag1"
[107] "Visa_fechaalta_lag1"
[108] "Visa_cconsumos_lag1"
[109] "mrentabilidad_rank_lag1"
[110] "mrentabilidad_annual_rank_lag1"
[111] "mcomisiones_rank_lag1"
[112] "mactivos_margen_rank_lag1"
[113] "mpasivos_margen_rank_lag1"
[114] "mcuenta_corriente_rank_lag1"
[115] "mcaja_ahorro_rank_lag1"
[116] "mcaja_ahorro_adicional_rank_lag1"
[117] "mcaja_ahorro_dolares_rank_lag1"
[118] "mcuentas_saldo_rank_lag1"
[119] "mautoservicio_rank_lag1"
[120] "mtarjeta_visa_consumo_rank_lag1"
[121] "mprestamos_personales_rank_lag1"
[122] "mpayroll_rank_lag1"
[123] "mcuenta_debitos_automaticos_rank_lag1"
[124] "mpagomiscuentas_rank_lag1"
[125] "mtarjeta_master_descuentos_rank_lag1"
[126] "mcomisiones_mantenimiento_rank_lag1"
[127] "mcomisiones_otras_rank_lag1"
[128] "mtransferencias_recibidas_rank_lag1"
[129] "mtransferencias_emitidas_rank_lag1"
[130] "matm_other_rank_lag1"
[131] "Master_mfinanciacion_limite_rank_lag1"
[132] "Master_msaldototal_rank_lag1"
[133] "Master_msaldopesos_rank_lag1"
[134] "Master_mconsumospesos_rank_lag1"
[135] "Master_mlimitecompra_rank_lag1"
[136] "Master_mpagominimo_rank_lag1"
[137] "Visa_mfinanciacion_limite_rank_lag1"
[138] "Visa_msaldototal_rank_lag1"
[139] "Visa_msaldopesos_rank_lag1"
[140] "Visa_mconsumospesos_rank_lag1"
[141] "Visa_mconsumosdolares_rank_lag1"
[142] "Visa_mlimitecompra_rank_lag1"
[143] "Visa_mpagado_rank_lag1"
[144] "Visa_mpagominimo_rank_lag1"
[145] "ctrx_quarter_normalizado_lag1"
[146] "vm_status03_lag1"
[147] "vm_status05_lag1"
[148] "vm_Fvencimiento_lag1"
[149] "vm_fultimo_cierre_lag1"
[150] "vm_fechaalta_lag1"
[151] "vm_cconsumos_lag1"
[152] "internet_lag2"
[153] "cliente_edad_lag2"
[154] "cliente_antiguedad_lag2"
[155] "cproductos_lag2"
[156] "ccaja_ahorro_lag2"
[157] "ctarjeta_debito_transacciones_lag2"
[158] "ctarjeta_visa_transacciones_lag2"
[159] "cprestamos_personales_lag2"
[160] "ccaja_seguridad_lag2"
[161] "cpayroll_trx_lag2"
[162] "ctarjeta_visa_debitos_automaticos_lag2"
[163] "ctarjeta_visa_descuentos_lag2"
[164] "ccomisiones_mantenimiento_lag2"
[165] "ccomisiones_otras_lag2"
[166] "cextraccion_autoservicio_lag2"
[167] "ccheques_depositados_lag2"
[168] "tcallcenter_lag2"
[169] "chomebanking_transacciones_lag2"
[170] "ctrx_quarter_lag2"
[171] "Master_Fvencimiento_lag2"
[172] "Master_fultimo_cierre_lag2"
[173] "Master_fechaalta_lag2"
[174] "Visa_Fvencimiento_lag2"
[175] "Visa_fultimo_cierre_lag2"
[176] "Visa_fechaalta_lag2"
[177] "Visa_cconsumos_lag2"
[178] "mrentabilidad_rank_lag2"
[179] "mrentabilidad_annual_rank_lag2"
[180] "mcomisiones_rank_lag2"
[181] "mactivos_margen_rank_lag2"
[182] "mpasivos_margen_rank_lag2"
[183] "mcuenta_corriente_rank_lag2"
[184] "mcaja_ahorro_rank_lag2"
[185] "mcaja_ahorro_dolares_rank_lag2"
[186] "mcuentas_saldo_rank_lag2"
[187] "mautoservicio_rank_lag2"
[188] "mtarjeta_master_consumo_rank_lag2"
[189] "mprestamos_personales_rank_lag2"
[190] "mplazo_fijo_dolares_rank_lag2"
[191] "mpayroll_rank_lag2"
[192] "mcuenta_debitos_automaticos_rank_lag2"
[193] "mttarjeta_visa_debitos_automaticos_rank_lag2"
[194] "mtarjeta_visa_descuentos_rank_lag2"
[195] "mcomisiones_mantenimiento_rank_lag2"
[196] "mcomisiones_otras_rank_lag2"
[197] "mtransferencias_recibidas_rank_lag2"
[198] "Master_mfinanciacion_limite_rank_lag2"
[199] "Master_mconsumosdolares_rank_lag2"
[200] "Master_mlimitecompra_rank_lag2"
[201] "Master_mpagominimo_rank_lag2"
[202] "Visa_mfinanciacion_limite_rank_lag2"
[203] "Visa_msaldototal_rank_lag2"
[204] "Visa_msaldopesos_rank_lag2"
[205] "Visa_mconsumospesos_rank_lag2"
[206] "Visa_mconsumosdolares_rank_lag2"
[207] "Visa_mlimitecompra_rank_lag2"
[208] "Visa_mpagospesos_rank_lag2"
[209] "Visa_mpagominimo_rank_lag2"
[210] "ctrx_quarter_normalizado_lag2"
[211] "foto_mes_formato_fecha_lag2"
[212] "mv_status07_lag2"
[213] "vm_Fvencimiento_lag2"
[214] "vm_fultimo_cierre_lag2"
[215] "vm_fechaalta_lag2"
[216] "vm_cconsumos_lag2"
[217] "cproductos_delta1"
[218] "cproductos_delta2"
[219] "cdescubierto_preacordado_delta2"
[220] "ctarjeta_debito_transacciones_delta2"
[221] "ctarjeta_visa_transacciones_delta2"
[222] "ctarjeta_visa_debitos_automaticos_delta2"
[223] "cpagomiscuentas_delta1"
[224] "cpagomiscuentas_delta2"
[225] "ccajeros_propios_descuentos_delta1"
[226] "ctarjeta_visa_descuentos_delta1"
[227] "ctarjeta_master_descuentos_delta1"
[228] "ccomisiones_mantenimiento_delta1"
[229] "ccomisiones_mantenimiento_delta2"
[230] "ctransferencias_recibidas_delta2"
[231] "cextraccion_autoservicio_delta2"
[232] "ccheques_depositados_delta2"
[233] "tcallcenter_delta2"
[234] "ccallcenter_transacciones_delta1"
[235] "ccallcenter_transacciones_delta2"
[236] "thomebanking_delta2"
[237] "chomebanking_transacciones_delta1"
[238] "chomebanking_transacciones_delta2"
[239] "ctrx_quarter_delta1"
[240] "ctrx_quarter_delta2"
[241] "tmobile_app_delta1"
[242] "tmobile_app_delta2"
[243] "Visa_cconsumos_delta1"
[244] "Visa_cconsumos_delta2"
[245] "mrentabilidad_rank_delta1"
[246] "mrentabilidad_rank_delta2"
[247] "mrentabilidad_annual_rank_delta1"
[248] "mrentabilidad_annual_rank_delta2"
[249] "mcomisiones_rank_delta1"
[250] "mcomisiones_rank_delta2"
[251] "mactivos_margen_rank_delta1"
[252] "mactivos_margen_rank_delta2"
[253] "mpasivos_margen_rank_delta1"
[254] "mpasivos_margen_rank_delta2"
[255] "mcuenta_corriente_rank_delta1"
[256] "mcuenta_corriente_rank_delta2"
[257] "mcaja_ahorro_rank_delta1"
[258] "mcaja_ahorro_rank_delta2"
[259] "mcaja_ahorro_dolares_rank_delta1"
[260] "mcaja_ahorro_dolares_rank_delta2"
[261] "mcuentas_saldo_rank_delta1"
[262] "mcuentas_saldo_rank_delta2"
[263] "mtarjeta_visa_consumo_rank_delta1"
[264] "mprestamos_personales_rank_delta2"
[265] "mplazo_fijo_dolares_rank_delta1"
[266] "mplazo_fijo_dolares_rank_delta2"
[267] "mpayroll_rank_delta2"
[268] "mttarjeta_visa_debitos_automaticos_rank_delta2"
[269] "mttarjeta_master_debitos_automaticos_rank_delta2"
[270] "mpagomiscuentas_rank_delta1"
[271] "mpagomiscuentas_rank_delta2"
[272] "mtarjeta_visa_descuentos_rank_delta1"
[273] "mcomisiones_mantenimiento_rank_delta1"
[274] "mcomisiones_mantenimiento_rank_delta2"
[275] "mcomisiones_otras_rank_delta1"
[276] "mcomisiones_otras_rank_delta2"
[277] "mtransferencias_recibidas_rank_delta2"
[278] "mextraccion_autoservicio_rank_delta2"
[279] "matm_rank_delta2"
[280] "matm_other_rank_delta1"
[281] "matm_other_rank_delta2"
[282] "Master_mfinanciacion_limite_rank_delta1"
[283] "Master_mfinanciacion_limite_rank_delta2"
[284] "Master_msaldototal_rank_delta1"
[285] "Master_mlimitecompra_rank_delta1"
[286] "Master_mlimitecompra_rank_delta2"
[287] "Master_mpagado_rank_delta1"
[288] "Master_mpagominimo_rank_delta1"
[289] "Visa_mfinanciacion_limite_rank_delta1"
[290] "Visa_mfinanciacion_limite_rank_delta2"
[291] "Visa_msaldototal_rank_delta2"
[292] "Visa_msaldopesos_rank_delta1"
[293] "Visa_msaldopesos_rank_delta2"
[294] "Visa_mconsumospesos_rank_delta1"
[295] "Visa_mconsumospesos_rank_delta2"
[296] "Visa_mlimitecompra_rank_delta2"
[297] "Visa_mpagado_rank_delta1"
[298] "Visa_mpagado_rank_delta2"
[299] "Visa_mpagospesos_rank_delta1"
[300] "Visa_mpagospesos_rank_delta2"
[301] "Visa_mconsumototal_rank_delta2"
[302] "Visa_mpagominimo_rank_delta1"
[303] "Visa_mpagominimo_rank_delta2"
[304] "ctrx_quarter_normalizado_delta1"
[305] "ctrx_quarter_normalizado_delta2"
[306] "vm_status02_delta2"
[307] "vm_status05_delta1"
[308] "vm_status06_delta1"
[309] "mv_status07_delta2"
[310] "vm_fultimo_cierre_delta2"
[311] "vm_cconsumos_delta1"
[312] "vm_cconsumos_delta2"
[313] "internet_tend6"
[314] "cliente_edad_tend6"
[315] "cproductos_tend6"
[316] "cdescubierto_preacordado_tend6"
[317] "ctarjeta_debito_transacciones_tend6"
[318] "ctarjeta_visa_transacciones_tend6"
[319] "ctarjeta_master_transacciones_tend6"
[320] "cseguro_accidentes_personales_tend6"
[321] "cpayroll_trx_tend6"
[322] "ccuenta_debitos_automaticos_tend6"
[323] "ctarjeta_visa_debitos_automaticos_tend6"
[324] "cpagomiscuentas_tend6"
[325] "ccomisiones_mantenimiento_tend6"
[326] "ccomisiones_otras_tend6"
[327] "ctransferencias_recibidas_tend6"
[328] "ctransferencias_emitidas_tend6"
[329] "tcallcenter_tend6"
[330] "ccallcenter_transacciones_tend6"
[331] "thomebanking_tend6"
[332] "chomebanking_transacciones_tend6"
[333] "ccajas_transacciones_tend6"
[334] "ccajas_consultas_tend6"
[335] "ccajas_extracciones_tend6"
[336] "ccajas_otras_tend6"
[337] "catm_trx_tend6"
[338] "ctrx_quarter_tend6"
[339] "tmobile_app_tend6"
[340] "cmobile_app_trx_tend6"
[341] "Master_status_tend6"
[342] "Master_Fvencimiento_tend6"
[343] "Master_fechaalta_tend6"
[344] "Master_cconsumos_tend6"
[345] "Visa_delinquency_tend6"
[346] "Visa_fultimo_cierre_tend6"
[347] "Visa_cconsumos_tend6"
[348] "mrentabilidad_rank_tend6"
[349] "mrentabilidad_annual_rank_tend6"
[350] "mcomisiones_rank_tend6"
[351] "mactivos_margen_rank_tend6"
[352] "mpasivos_margen_rank_tend6"
[353] "mcuenta_corriente_rank_tend6"
[354] "mcaja_ahorro_rank_tend6"
[355] "mcaja_ahorro_dolares_rank_tend6"
[356] "mcuentas_saldo_rank_tend6"
[357] "mautoservicio_rank_tend6"
[358] "mtarjeta_visa_consumo_rank_tend6"
[359] "mtarjeta_master_consumo_rank_tend6"
[360] "mprestamos_personales_rank_tend6"
[361] "mplazo_fijo_dolares_rank_tend6"
[362] "mpayroll_rank_tend6"
[363] "mcuenta_debitos_automaticos_rank_tend6"
[364] "mttarjeta_visa_debitos_automaticos_rank_tend6"
[365] "mttarjeta_master_debitos_automaticos_rank_tend6"
[366] "mcomisiones_mantenimiento_rank_tend6"
[367] "mcomisiones_otras_rank_tend6"
[368] "mtransferencias_recibidas_rank_tend6"
[369] "mtransferencias_emitidas_rank_tend6"
[370] "mextraccion_autoservicio_rank_tend6"
[371] "mcheques_depositados_rank_tend6"
[372] "matm_rank_tend6"
[373] "matm_other_rank_tend6"
[374] "Master_mfinanciacion_limite_rank_tend6"
[375] "Master_msaldopesos_rank_tend6"
[376] "Master_mconsumospesos_rank_tend6"
[377] "Master_mconsumosdolares_rank_tend6"
[378] "Master_mlimitecompra_rank_tend6"
[379] "Master_mpagado_rank_tend6"
[380] "Master_mpagominimo_rank_tend6"
[381] "Visa_mfinanciacion_limite_rank_tend6"
[382] "Visa_msaldototal_rank_tend6"
[383] "Visa_msaldopesos_rank_tend6"
[384] "Visa_msaldodolares_rank_tend6"
[385] "Visa_mconsumosdolares_rank_tend6"
[386] "Visa_mlimitecompra_rank_tend6"
[387] "Visa_mpagado_rank_tend6"
[388] "Visa_mpagospesos_rank_tend6"
[389] "Visa_mpagominimo_rank_tend6"
[390] "kmes_tend6"
[391] "ctrx_quarter_normalizado_tend6"
[392] "vm_status03_tend6"
[393] "vm_status04_tend6"
[394] "vm_Fvencimiento_tend6"
[395] "vm_cconsumos_tend6"
[396] "rf_001_006"
[397] "rf_001_007"
[398] "rf_001_001"
[399] "rf_002_008"
[400] "rf_003_014"
[401] "rf_006_006"
[402] "rf_007_003"
[403] "rf_007_008"
[404] "rf_007_009"
[405] "rf_007_001"
[406] "rf_008_002"
[407] "rf_009_004"
[408] "rf_010_007"
[409] "rf_011_010"
[410] "rf_011_012"
[411] "rf_012_001"
[412] "rf_013_015"
[413] "rf_013_003"
[414] "rf_013_001"
[415] "rf_015_007"
[416] "rf_015_012"
[417] "rf_015_009"
[418] "rf_017_002"
[419] "rf_018_001"
[420] "rf_002_011"
[421] "rf_003_003"
[422] "rf_006_013"
[423] "rf_006_005"
[424] "rf_008_009"
[425] "rf_009_001"
[426] "rf_010_008"
[427] "rf_011_014"
[428] "rf_011_001"
[429] "rf_013_008"
[430] "rf_014_015"
[431] "rf_016_001"
[432] "rf_017_015"
[433] "rf_004_012"
[434] "rf_004_011"
[435] "rf_004_001"
[436] "rf_007_007"
[437] "rf_008_001"
[438] "rf_010_009"
[439] "rf_013_000"
[440] "rf_014_001"
[441] "rf_014_010"
[442] "rf_014_005"
[443] "rf_015_001"
[444] "rf_018_000"

### 9.7.2 Modelado

#### 9.7.2.1 Training Strategy

Se hace una estrategia de entrenamiento muy sencilla, tomando todos los meses posibles, SIN eliminar nada x pandemia ni por ningun otro motivo

* future = 202109  obviamente completo

* final_train =  [ 201901, 202107 ] sin undersampling de los CONTINUA

* training
   * testing = NO HAY
   * validation =  202107   completo, sin undersampling
   * training = [ 201901, 202105 ]  donde se consideran el 20% de los CONTINUA

In [51]:
PARAM$trainingstrategy$validate <- c(202107)

PARAM$trainingstrategy$training <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105
)

PARAM$trainingstrategy$training_pct <- 0.2


PARAM$trainingstrategy$positivos <- c( "BAJA+1", "BAJA+2")

In [52]:
# seteo la clase01   1={BAJA+1, BAJA+2}   0={CONTINUA}
dataset[, clase01 := ifelse( clase_ternaria %in% PARAM$trainingstrategy$positivos, 1, 0 )]

In [53]:
# los campos en los que se entrena
campos_buenos <- copy( setdiff(
    colnames(dataset), c("clase_ternaria","clase01","azar"))
)

In [54]:
# preparo para que se puede hacer undersampling de los CONTINUA
#  solamente por un tema de VELOCIDAD
set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
dataset[, azar:=runif(nrow(dataset))]

# undersampling de los CONTINUA
dataset[, fold_train :=  foto_mes %in%  PARAM$trainingstrategy$training &
    (clase_ternaria %in% c("BAJA+1", "BAJA+2") |
     azar < PARAM$trainingstrategy$training_pct ) ]


if( !require("lightgbm")) install.packages("lightgbm")
require("lightgbm")

dtrain <- lgb.Dataset(
  data= data.matrix(dataset[fold_train == TRUE, campos_buenos, with = FALSE]),
  label= dataset[fold_train == TRUE, clase01],
  free_raw_data= TRUE
)

In [55]:
# datos de validation
dvalidate <- lgb.Dataset(
  data= data.matrix(dataset[foto_mes %in% PARAM$trainingstrategy$validate, campos_buenos, with = FALSE]),
  label= dataset[foto_mes %in% PARAM$trainingstrategy$validate, clase01],
  free_raw_data= TRUE
)

nrow(dvalidate)

[1] 164479

####  9.7.2.2. Hyperparameter Tuning

* Clase binaria que se optimiza :  positivos = [ BAJA+1, BAJA+2 ]

* Metrica que se optimiza **AUC** Area Under Curve de la  ROC Curve

es muy importante notar que intencionalmente  **NO** se está optimizando la funcion de ganancia del problema

* Cantidad de iteraciones inteligentes de la Optimizacion Bayesiana = **40**

In [56]:
# paquetes necesarios para la Bayesian Optimization
if(!require("DiceKriging")) install.packages("DiceKriging")
require("DiceKriging")

if(!require("mlrMBO")) install.packages("mlrMBO")
require("mlrMBO")

Loading required package: DiceKriging

Loading required package: mlrMBO

Loading required package: mlr

Loading required package: ParamHelpers

Attaching package: ‘ParamHelpers’

The following object is masked from ‘package:R.utils’:

    isVector

Attaching package: ‘mlr’

The following objects are masked from ‘package:R.utils’:

    resample, setThreshold

Loading required package: smoof

Loading required package: checkmate

Attaching package: ‘checkmate’

The following object is masked from ‘package:DiceKriging’:

    checkNames

The following object is masked from ‘package:R.utils’:

    asInt

Attaching package: ‘smoof’

The following objects are masked from ‘package:R.oo’:

    getDescription, getName

Definición de la Bayesian Optimization
<br> Si se desea optimizar un hiperparámetro que esta como fijo, debe QUITARSE de param_fijos y agregarse a PARAM$hipeparametertuning$hs

In [57]:
# 40 es el minimo razonable,  un buen analista Sr aumentara este valor
PARAM$hipeparametertuning$num_interations <- 30

# parametros fijos del LightGBM
PARAM$lgbm$param_fijos <- list(
  objective= "binary",
  metric= "auc",
  first_metric_only= TRUE,
  boost_from_average= TRUE,
  feature_pre_filter= FALSE,
  verbosity= -100,
  force_row_wise= TRUE, # para evitar warning
  seed= PARAM$semilla_primigenia,
  extra_trees= FALSE,

  num_leaves= 128,
  max_depth= -1L, # -1 significa no limitar,  por ahora lo dejo fijo
  min_gain_to_split= 0.0, # min_gain_to_split >= 0.0
  min_data_in_leaf= 0,
  min_sum_hessian_in_leaf= 0.001, #  min_sum_hessian_in_leaf >= 0.0
  lambda_l1= 0.0, # lambda_l1 >= 0.0
  lambda_l2= 0.0, # lambda_l2 >= 0.0

  bagging_fraction= 1.0, # 0.0 < bagging_fraction <= 1.0
  pos_bagging_fraction= 1.0, # 0.0 < pos_bagging_fraction <= 1.0
  neg_bagging_fraction= 1.0, # 0.0 < neg_bagging_fraction <= 1.0
  is_unbalance= FALSE, #
  scale_pos_weight= 1.0, # scale_pos_weight > 0.0

  drop_rate= 0.1, # 0.0 < neg_bagging_fraction <= 1.0
  max_drop= 50, # <=0 means no limit
  skip_drop= 0.5, # 0.0 <= skip_drop <= 1.0

  max_bin= 31,
  early_stopping_rounds= 0
)

In [58]:
PARAM$hipeparametertuning$hs <- makeParamSet(
  makeNumericParam("num_iterations", lower= 8, upper= 12, trafo= function(x) round(2^x) ), # 256..4096 was 2..10 (4..1024) - covers HT 1018..3000
  makeNumericParam("num_leaves", lower= 5, upper= 8, trafo= function(x) round(2^x) ), # 32..256 FIX was 4..2048 (2040 unrealistic)
  makeNumericParam("learning_rate", lower= -6, upper= -3.2, trafo= function(x) 2^x ), # 0.015..0.108 was -7..-0.1 (0.007..0.93) - narrow around HT 0.02-0.05
  makeNumericParam("feature_fraction", lower= 0.4, upper= 0.8), # was 0.05..0.90 - HT optimum 0.6
  makeNumericParam("min_data_in_leaf", lower= 4, upper= 10, trafo= function(x) round(2^x) ), # 16..1024 NEW from HT 30..400
  makeNumericParam("lambda_l2", lower= 4, upper= 9, trafo= function(x) 2^x), # 16..512 NEW from HT 100..300
  makeNumericParam("bagging_fraction", lower= 0.7, upper= 1.0) # NEW from HT 0.7..1
)

Función "señora caja negra"  que es llamada para verificar la realidad por la Bayesian Optimization

In [59]:
# En  x llegan los parmaetros de la bayesiana
#  devuelve la AUC en validate del modelo entrenado
#  en el parametro x llegan los hiperparámetros que se estan optimizando

EstimarGanancia_AUC_lightgbm <- function(x) {

  # x pisa (o agrega) a param_fijos
  param_completo <- modifyList(PARAM$lgbm$param_fijos, x)

  # entreno LightGBM
  modelo_train <- lgb.train(
    data= dtrain,
    valids= list(valid = dvalidate),
    eval= "auc",
    param= param_completo,
    verbose= -100
  )

  # recupero la AUC en validation
  AUC <- modelo_train$record_evals$valid$auc$eval[[x$num_iterations]]


  message(format(Sys.time(), "%a %b %d %X %Y  "),
    toString(x),
    " AUC ", AUC
  )

  # hago espacio en la memoria
  rm(modelo_train)
  gc(full= TRUE, verbose= FALSE)

  return(AUC)
}

seteo de la Bayesian Optimization (complejo)
<br> copiado y pegado de la documentación de la librería

In [60]:
configureMlr(show.learner.output = FALSE)

# configuro la busqueda bayesiana,  los hiperparametros que se van a optimizar
# por favor, no desesperarse por lo complejo
obj.fun <- makeSingleObjectiveFunction(
    fn= EstimarGanancia_AUC_lightgbm, # la funcion que voy a maximizar
    minimize= FALSE, # estoy Maximizando AUC
    noisy= FALSE,
    par.set= PARAM$hipeparametertuning$hs,
    has.simple.signature= FALSE # paso los parametros en una lista
)

# cada 600 segundos guardo el resultado intermedio
ctrl <- makeMBOControl(
    save.on.disk.at.time= 600,
    save.file.path= "HT.RDATA"
)

# indico la cantidad de iteraciones que va a tener la Bayesian Optimization
ctrl <- setMBOControlTermination(
    ctrl,
    iters= PARAM$hipeparametertuning$num_interations  # cantidad de iteraciones inteligentes
)

# defino el método estandar para la creacion de los puntos iniciales
#   los "No Inteligentes"
ctrl <- setMBOControlInfill(ctrl, crit = makeMBOInfillCritEI())

# mas configuraciones
surr.km <- makeLearner(
    "regr.km",
    predict.type= "se",
    covtype= "matern3_2",
    control= list(trace = TRUE)
)

Corrida de la Bayesian Optimization,  aqui se hace el trabajo pesado
<br> por favor no se asuste con los warnings que pudieran aparecer

Si corrío a medias y llegó a las iteraciones inteligentes, en el archivo binario HT.RDATA quedó lo ya procesado y es utilizado para retomar la corrida desde lo último que llegó a grabar.

In [61]:
# inicio la optimizacion bayesiana - warm-start DESACTIVADO temporalmente, solo hs fixeada 32..256
if (!file.exists("HT.RDATA")) {
  bayesiana_salida <- mbo(obj.fun, learner= surr.km, control= ctrl)
} else {
  bayesiana_salida <- mboContinue("HT.RDATA")
}

Computing y column(s) for design. Not provided.

Thu Sep 03 21:23:12 2026  2685, 106, 0.0363221281333659, 0.670158835119676, 186, 226.107785287202, 0.886671091462922 AUC 0.936619603154568

Thu Sep 03 21:27:18 2026  1300, 81, 0.0270718314596404, 0.600542681105107, 105, 33.000255686248, 0.82027048456329 AUC 0.938294366843666

Thu Sep 03 21:28:46 2026  547, 87, 0.0332603528740547, 0.722111742976611, 38, 65.5887484409189, 0.803044241057523 AUC 0.938055719622621

Thu Sep 03 21:32:58 2026  1641, 96, 0.0484764132862978, 0.63446499378956, 163, 115.195357474173, 0.86591978895941 AUC 0.935928038017846

Thu Sep 03 21:41:59 2026  2488, 62, 0.0612995436108654, 0.516831154885375, 457, 24.6370775960968, 0.786922510342778 AUC 0.93499654647039

Thu Sep 03 21:44:35 2026  832, 157, 0.0224089375524169, 0.762063695702061, 270, 124.560473661234, 0.807210177798423 AUC 0.938580024285802

Thu Sep 03 21:48:56 2026  1106, 74, 0.0949665564712748, 0.480209453370188, 72, 201.278904626725, 0.844961677251823 AUC 0.935902259006352

Thu Sep 03 22:02:09 2026  3639, 67, 0.0572148379147329, 0.492834771526559, 395, 75.1344098123573, 0.920552333385291 AUC 0.935498032495805

Thu Sep 03 22:05:19 2026  686, 165, 0.030453948880873, 0.540602939376936, 503, 21.9842108070179, 0.73688534527668 AUC 0.93824815033666

Thu Sep 03 22:06:09 2026  431, 42, 0.0854412789652849, 0.682703318427451, 39, 41.7141701522788, 0.879767155063238 AUC 0.936683240272968

Thu Sep 03 22:08:26 2026  589, 68, 0.0167745813585521, 0.589786842276796, 63, 302.617813525744, 0.941291718695371 AUC 0.934927294274357

Thu Sep 03 22:17:33 2026  2120, 135, 0.0161070596271028, 0.466293494863147, 85, 80.9024783582535, 0.834660178897411 AUC 0.938576843007829

Thu Sep 03 22:22:10 2026  1473, 143, 0.0784027616707577, 0.701430740077154, 318, 136.503844566458, 0.899034629138334 AUC 0.935723761955909

Thu Sep 03 22:29:36 2026  1870, 55, 0.044318232903887, 0.576363843762108, 33, 160.991522398467, 0.911794207457066 AUC 0.937073769436086

Thu Sep 03 22:30:30 2026  385, 46, 0.0236876138305704, 0.656588265472508, 241, 54.5315958314947, 0.78551388027207 AUC 0.935660980199289

Thu Sep 03 22:32:27 2026  494, 244, 0.0742457802188101, 0.794217279389779, 29, 183.602355639385, 0.967749620843295 AUC 0.936489285062783

Thu Sep 03 22:40:29 2026  1750, 191, 0.0185312840669688, 0.455291049585005, 831, 399.948045706443, 0.76657748879638 AUC 0.939202448962939

Thu Sep 03 22:42:43 2026  875, 50, 0.0199419259235602, 0.688636507155598, 19, 247.756754747654, 0.745998199066991 AUC 0.936958849140675

Thu Sep 03 22:56:53 2026  3968, 188, 0.104134139277714, 0.783996640169032, 217, 394.612048250267, 0.705496163019392 AUC 0.934941689011345

Thu Sep 03 23:00:00 2026  737, 39, 0.0217415364803067, 0.558586864459544, 23, 45.8656780747285, 0.995688441676732 AUC 0.937605266330453

Thu Sep 03 23:01:41 2026  349, 117, 0.0650362534749303, 0.554427697032116, 130, 93.3209941743885, 0.719523839300855 AUC 0.938754542491206

Thu Sep 03 23:05:59 2026  1006, 208, 0.0513710403912663, 0.411300174095437, 925, 57.5490203406927, 0.97989206816994 AUC 0.937689100775216

Thu Sep 03 23:10:06 2026  1170, 34, 0.0278515687082472, 0.436610219508026, 114, 20.4372894782281, 0.728822986281552 AUC 0.938057703907832

Thu Sep 03 23:11:04 2026  272, 232, 0.0425141796781247, 0.626976479489415, 18, 18.1020405605144, 0.948844190046395 AUC 0.937655945873775

Thu Sep 03 23:11:42 2026  289, 52, 0.0885063262725628, 0.73669952107043, 709, 28.3539917277386, 0.975364768347307 AUC 0.93711107271373

Thu Sep 03 23:22:34 2026  2909, 35, 0.0698387173020301, 0.513408770712331, 607, 339.97985115885, 0.755718436965288 AUC 0.936200163790736

Thu Sep 03 23:23:58 2026  332, 128, 0.033804813083108, 0.423338299709657, 46, 493.440629054482, 0.925490319748439 AUC 0.934769718910703

Thu Sep 03 23:30:38 2026  3188, 103, 0.0401001183523583, 0.751373329159922, 56, 35.652396425777, 0.859654561370579 AUC 0.936290720403004

[mbo] 0: num_iterations=2.68e+03; num_leaves=106; learning_rate=0.0363; feature_fraction=0.67; min_data_in_leaf=186; lambda_l2=226; bagging_fraction=0.887 : y = 0.937 : 466.1 secs : initdesign

[mbo] 0: num_iterations=1.3e+03; num_leaves=81; learning_rate=0.0271; feature_fraction=0.601; min_data_in_leaf=105; lambda_l2=33; bagging_fraction=0.82 : y = 0.938 : 245.1 secs : initdesign

[mbo] 0: num_iterations=547; num_leaves=87; learning_rate=0.0333; feature_fraction=0.722; min_data_in_leaf=38; lambda_l2=65.6; bagging_fraction=0.803 : y = 0.938 : 88.3 secs : initdesign

[mbo] 0: num_iterations=1.64e+03; num_leaves=96; learning_rate=0.0485; feature_fraction=0.634; min_data_in_leaf=163; lambda_l2=115; bagging_fraction=0.866 : y = 0.936 : 252.3 secs : initdesign

[mbo] 0: num_iterations=2.49e+03; num_leaves=62; learning_rate=0.0613; feature_fraction=0.517; min_data_in_leaf=457; lambda_l2=24.6; bagging_fraction=0.787 : y = 0.935 : 540.7 secs : initdesign

[mbo] 0: num_iterations=832; num_leaves=157; learning_rate=0.0224; feature_fraction=0.762; min_data_in_leaf=270; lambda_l2=125; bagging_fraction=0.807 : y = 0.939 : 155.6 secs : initdesign

[mbo] 0: num_iterations=1.11e+03; num_leaves=74; learning_rate=0.095; feature_fraction=0.48; min_data_in_leaf=72; lambda_l2=201; bagging_fraction=0.845 : y = 0.936 : 261.7 secs : initdesign

[mbo] 0: num_iterations=3.64e+03; num_leaves=67; learning_rate=0.0572; feature_fraction=0.493; min_data_in_leaf=395; lambda_l2=75.1; bagging_fraction=0.921 : y = 0.935 : 792.6 secs : initdesign

[mbo] 0: num_iterations=686; num_leaves=165; learning_rate=0.0305; feature_fraction=0.541; min_data_in_leaf=503; lambda_l2=22; bagging_fraction=0.737 : y = 0.938 : 189.7 secs : initdesign

[mbo] 0: num_iterations=431; num_leaves=42; learning_rate=0.0854; feature_fraction=0.683; min_data_in_leaf=39; lambda_l2=41.7; bagging_fraction=0.88 : y = 0.937 : 50.3 secs : initdesign

[mbo] 0: num_iterations=589; num_leaves=68; learning_rate=0.0168; feature_fraction=0.59; min_data_in_leaf=63; lambda_l2=303; bagging_fraction=0.941 : y = 0.935 : 136.9 secs : initdesign

[mbo] 0: num_iterations=2.12e+03; num_leaves=135; learning_rate=0.0161; feature_fraction=0.466; min_data_in_leaf=85; lambda_l2=80.9; bagging_fraction=0.835 : y = 0.939 : 547.2 secs : initdesign

[mbo] 0: num_iterations=1.47e+03; num_leaves=143; learning_rate=0.0784; feature_fraction=0.701; min_data_in_leaf=318; lambda_l2=137; bagging_fraction=0.899 : y = 0.936 : 276.7 secs : initdesign

[mbo] 0: num_iterations=1.87e+03; num_leaves=55; learning_rate=0.0443; feature_fraction=0.576; min_data_in_leaf=33; lambda_l2=161; bagging_fraction=0.912 : y = 0.937 : 445.8 secs : initdesign

[mbo] 0: num_iterations=385; num_leaves=46; learning_rate=0.0237; feature_fraction=0.657; min_data_in_leaf=241; lambda_l2=54.5; bagging_fraction=0.786 : y = 0.936 : 54.9 secs : initdesign

[mbo] 0: num_iterations=494; num_leaves=244; learning_rate=0.0742; feature_fraction=0.794; min_data_in_leaf=29; lambda_l2=184; bagging_fraction=0.968 : y = 0.936 : 116.5 secs : initdesign

[mbo] 0: num_iterations=1.75e+03; num_leaves=191; learning_rate=0.0185; feature_fraction=0.455; min_data_in_leaf=831; lambda_l2=400; bagging_fraction=0.767 : y = 0.939 : 482.4 secs : initdesign

[mbo] 0: num_iterations=875; num_leaves=50; learning_rate=0.0199; feature_fraction=0.689; min_data_in_leaf=19; lambda_l2=248; bagging_fraction=0.746 : y = 0.937 : 133.5 secs : initdesign

[mbo] 0: num_iterations=3.97e+03; num_leaves=188; learning_rate=0.104; feature_fraction=0.784; min_data_in_leaf=217; lambda_l2=395; bagging_fraction=0.705 : y = 0.935 : 850.2 secs : initdesign

[mbo] 0: num_iterations=737; num_leaves=39; learning_rate=0.0217; feature_fraction=0.559; min_data_in_leaf=23; lambda_l2=45.9; bagging_fraction=0.996 : y = 0.938 : 186.6 secs : initdesign

[mbo] 0: num_iterations=349; num_leaves=117; learning_rate=0.065; feature_fraction=0.554; min_data_in_leaf=130; lambda_l2=93.3; bagging_fraction=0.72 : y = 0.939 : 100.9 secs : initdesign

[mbo] 0: num_iterations=1.01e+03; num_leaves=208; learning_rate=0.0514; feature_fraction=0.411; min_data_in_leaf=925; lambda_l2=57.5; bagging_fraction=0.98 : y = 0.938 : 258.9 secs : initdesign

[mbo] 0: num_iterations=1.17e+03; num_leaves=34; learning_rate=0.0279; feature_fraction=0.437; min_data_in_leaf=114; lambda_l2=20.4; bagging_fraction=0.729 : y = 0.938 : 246.1 secs : initdesign

[mbo] 0: num_iterations=272; num_leaves=232; learning_rate=0.0425; feature_fraction=0.627; min_data_in_leaf=18; lambda_l2=18.1; bagging_fraction=0.949 : y = 0.938 : 58.0 secs : initdesign

[mbo] 0: num_iterations=289; num_leaves=52; learning_rate=0.0885; feature_fraction=0.737; min_data_in_leaf=709; lambda_l2=28.4; bagging_fraction=0.975 : y = 0.937 : 38.4 secs : initdesign

[mbo] 0: num_iterations=2.91e+03; num_leaves=35; learning_rate=0.0698; feature_fraction=0.513; min_data_in_leaf=607; lambda_l2=340; bagging_fraction=0.756 : y = 0.936 : 652.2 secs : initdesign

[mbo] 0: num_iterations=332; num_leaves=128; learning_rate=0.0338; feature_fraction=0.423; min_data_in_leaf=46; lambda_l2=493; bagging_fraction=0.925 : y = 0.935 : 83.5 secs : initdesign

[mbo] 0: num_iterations=3.19e+03; num_leaves=103; learning_rate=0.0401; feature_fraction=0.751; min_data_in_leaf=56; lambda_l2=35.7; bagging_fraction=0.86 : y = 0.936 : 400.0 secs : initdesign

Saved the current state after iteration 1 in the file HT.RDATA.

Thu Sep 03 23:38:02 2026  1646, 224, 0.0203098123262139, 0.428155423909685, 685, 114.843213018843, 0.808230090613805 AUC 0.938871837507236

la bayesian optimization ha corrido, extraigo los mejores hiperparametros

In [ ]:
# almaceno los resultados de la Bayesian Optimization
# y capturo los mejores hiperparametros encontrados

tb_bayesiana <- as.data.table(bayesiana_salida$opt.path)

# ordeno en forma descendente por AUC = y
setorder(tb_bayesiana, -y, -num_iterations)

# grabo para eventualmente poder utilizarlos en OTRA corrida
fwrite( tb_bayesiana,
  file="BO_log.txt",
  sep="\t"
)

# los mejores hiperparámetros son los que quedaron en el registro 1 de la tabla
PARAM$out$lgbm$mejores_hiperparametros <- tb_bayesiana[
  1, # el primero es el de mejor AUC
  setdiff(colnames(tb_bayesiana),
    c("y","dob","eol","error.message","exec.time","ei","error.model",
      "train.time","prop.type","propose.time","se","mean","iter")),
  with= FALSE
]

print(PARAM$out$lgbm$mejores_hiperparametros)

### 9.7.3 Produccion

#### Final Training
Construyo el modelo final, que es uno solo, no hace ningun tipo de particion < training, validation, testing>]

##### Final Training Dataset

Aqui esta la gran decision de en qué meses hago el Final Training
<br> debo utilizar los mejores hiperparámetros que encontré en la optimización bayesiana

In [ ]:
PARAM$trainingstrategy$final_train <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105, 202106,
  202107
)

dataset[, fold_final_train := foto_mes %in% PARAM$trainingstrategy$final_train ]

# creo el dfinal_train en formato  LightGBM
dfinal_train <- lgb.Dataset(
  data= data.matrix(dataset[fold_final_train == TRUE, campos_buenos, with= FALSE]),
  label= dataset[fold_final_train == TRUE, clase01],
  free_raw_data= TRUE
)

nrow( dfinal_train) # verifico el tamaño

##### Final Training Hyperparameters

In [ ]:
# uno los parametros fijos y los mejores encontrados de los variables
fijos <- copy(PARAM$lgbm$param_fijos)

# quito lo que optimice en la Bayesian Optimization
fijos$num_iterations <- NULL
fijos$early_stopping_rounds <- NULL
fijos$num_leaves <- NULL
fijos$min_data_in_leaf <- NULL
fijos$lambda_l2 <- NULL
fijos$bagging_fraction <- NULL
fijos$min_sum_hessian_in_leaf <- NULL

# agrego a los hiperparametros fijos los que encontre con la Bayesian Optimization
param_final <- copy(fijos)

x <- PARAM$out$lgbm$mejores_hiperparametros
param_final$num_iterations <- round( 2^x$num_iterations )
param_final$num_leaves <- round( 2^x$num_leaves )
param_final$learning_rate <- 2^x$learning_rate
param_final$feature_fraction <- x$feature_fraction
param_final$min_data_in_leaf <- round( 2^x$min_data_in_leaf )
param_final$lambda_l2 <- 2^x$lambda_l2
param_final$bagging_fraction <- x$bagging_fraction

In [ ]:
param_final

##### Training
Genero el modelo final, siempre sobre TODOS los datos de  final_train, sin hacer ningun tipo de undersampling de la clase mayoritaria

In [ ]:
# poner este valor en 5 o en 1  si se está muy ajustado de tiempo

PARAM$FT$semillerio <- 10  # cantidad de semillas

In [ ]:
if(!require("primes")) install.packages("primes")
require("primes")

In [ ]:
primos <- generate_primes(min = 100000, max = 1000000)
set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
# me quedo con PARAM$semillerio  primos al azar
PARAM$FT$semillas <- sample(primos)[seq(PARAM$FT$semillerio)]

cat( PARAM$FT$semillas)

In [ ]:
primero <- TRUE

crear_modelo_final <- function( sem ) {

  nombre_arch <- paste0( "./modelos/modelo_", sem, ".txt")
  if( !file.exists(nombre_arch) )
  {
    param_final$seed <- sem

    set.seed(sem, kind = "L'Ecuyer-CMRG")
    final_model <- lgb.train(
      data= dfinal_train,
      param= param_final,
      verbose= -100
    )

    lgb.save(final_model, nombre_arch) # grabo el modelo"

    # grabo la primer importancia de variables
    #  Natalia : da lo mismo cual se guarda
    if( primero)
    {
      primero <<- FALSE
      tb_importancia <- as.data.table(lgb.importance(final_model))
      archivo_importancia <- "impo.txt"

      fwrite( tb_importancia,
        file= archivo_importancia,
        sep= "\t"
      )
    }

    rm(final_model)
    gc(full = TRUE, verbose=FALSE)
  }
}

In [ ]:
gc(full = TRUE, verbose=FALSE)
dir.create("modelos", showWarnings =FALSE)

primero <- TRUE
for( sem in PARAM$FT$semillas)  crear_modelo_final(sem)

#### Scoring

Aplico el modelo final a los datos del futuro

In [ ]:
PARAM$trainingstrategy$future <- c(202109)

dfuture <- dataset[ foto_mes %in% PARAM$trainingstrategy$future ]

In [ ]:
# aplico final_model   a dfuture

tb_prediccion <- dfuture[, list(numero_de_cliente)]
tb_prediccion[, prob := 0]

datos_matrix <- data.matrix(dfuture[, campos_buenos, with= FALSE])

In [ ]:
agregar_a_ensemble <- function( sem ) {

  nombre_arch <- paste0( "./modelos/modelo_", sem, ".txt")
  final_model <- lgb.load(nombre_arch)

  prediccion <- predict(
    final_model,
    datos_matrix
  )

  tb_prediccion[, paste0("prob_", isem) := prediccion]
  tb_prediccion[, prob := prob + prediccion]

  rm(final_model)
  rm(prediccion)
  gc(full = TRUE, verbose=FALSE)
}

In [ ]:
for( isem in seq(length(PARAM$FT$semillas)) )
{
  sem <- PARAM$FT$semillas[ isem ]
  agregar_a_ensemble( sem )
  gc(full = TRUE, verbose=FALSE)
}

rm( datos_matrix)
gc(full = TRUE, verbose=FALSE)

tb_prediccion[, prob := prob /length(PARAM$FT$semillas) ]

In [ ]:
# veo que hay en tb_prediccion
tb_prediccion

In [ ]:
# grabo las probabilidad del modelo
#  me va a ser util para hacer Ensembles de modelos
fwrite(tb_prediccion,
  file= "prediccion.txt",
  sep= "\t"
)

#### Kaggle Competition Submit

Genero las salidas y hago los submits a Kaggles

In [ ]:
# genero archivos con los  "envios" mejores
# suba TODOS los archivos a Kaggle

PARAM$kaggle$competencia <- "data-mining-senior-2026-b"
PARAM$kaggle$cortes <- seq(8000, 12000, by = 500)

# ordeno por probabilidad descendente
setorder(tb_prediccion, -prob)

dir.create("kaggle")

for (envios in PARAM$kaggle$cortes) {

  tb_prediccion[, Predicted := 0L] # seteo inicial a 0
  tb_prediccion[1:envios, Predicted := 1L] # marclo los primeros

  archivo_kaggle <- paste0(
    "./kaggle/KA",
    PARAM$experimento, "_",
    "s", length(PARAM$FT$semillas), "_",
    envios, ".csv")

  # grabo el archivo
  fwrite(tb_prediccion[, list(numero_de_cliente, Predicted)],
    file= archivo_kaggle,
    sep= ","
  )

  # subida a Kaggle, armo la linea de comando
  comando <- "kaggle competitions submit"
  competencia <- paste("-c", PARAM$kaggle$competencia)
  arch <- paste( "-f", archivo_kaggle)

  mensaje <- paste0("-m 'envios=", envios,
  "  semilla=", PARAM$semilla_primigenia,
    "'" )

  linea <- paste( comando, competencia, arch, mensaje)

  Sys.sleep(30)
  salida <- system(linea, intern=TRUE) # el submit a Kaggle
  cat(salida, "\n")
}

In [ ]:
# grabo los parametros
if( !require("yaml")) install.packages("yaml")
require("yaml")

write_yaml( PARAM, file="PARAM.yml")

In [ ]:
format(Sys.time(), "%a %b %d %X %Y")